### ISSUE TITLE
gnome import error: linux-gnu.so: undefined symbol: gdImageBmp

### ISSUE THREAD

**Issue by moisespr123** [NOAA-ORR-ERD/PyGnome#100]
Hello,

I'm trying to get PyGnome running without using Conda. While the installation and the dependencies seem to install, I get the following issue when attempting to import PyGnome:

```
import gnome
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/py_gd-1.1.1-py3.6-linux-x86_64.egg/py_gd/__init__.py", line 52, in <module>
    from .py_gd import *
ImportError: /usr/local/lib64/python3.6/site-packages/py_gd-1.1.1-py3.6-linux-x86_64.egg/py_gd/py_gd.cpython-36m-x86_64-linux-gnu.so: undefined symbol: gdImageBmp

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/PyGnome/py_gnome/gnome/__init__.py", line 117, in <module>
    check_dependency_versions()
  File "/PyGnome/py_gnome/gnome/__init__.py", line 45, in check_dependency_versions
    module = importlib.import_module(name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib64/python3.6/site-packages/py_gd-1.1.1-py3.6-linux-x86_64.egg/py_gd/__init__.py", line 54, in <module>
    if err.message.startswith("DLL load failed:"):
AttributeError: 'ImportError' object has no attribute 'message'
```

I have installed the `gd gd-devel` packages, but it seems there is an issue between it and `py_gd` that PyGnome use? Do you think of any dependency that I may be missing?

This is only if I don't use Conda. The Conda method does work fine.

Thanks for your help,
-Moisés

**Comment by ChrisBarker-NOAA** [comment]
This is really an issue with py_gd:

https://github.com/NOAA-ORR-ERD/py_gd

It looks like something went wrong with that build.

Could you try grabbing that code, building it, and running its tests, and see what happens?

Or, if you've already built it (which it looks like you did somehow) -- start with the tests.

And post any issues on that repo.

We've only built it with conda for a while, so there may be some issues there.

**Comment by moisespr123** [comment]
Thank you. I'll rebuild again using the libgd.tar.bzip2 package from the conda repository instead of using the system repository package. I'll open an issue there if the issue still persist.

**Comment by ChrisBarker-NOAA** [comment]
On Wed, Jul 14, 2021 at 11:51 AM Moises Cardona ***@***.***>
wrote:

> Thank you. I'll rebuild again using the libgd.tar.bzip2 package from the
> conda repository instead of using the system repository package. I'll open
> an issue there if the issue still persist.
>
>
NOTE: py_gd is a wrapper around the libgd C library -- it needs to be built
against libgd. YOu may not have a problem with the system libgd -- it
should work -- it's probably an issue with py_gd.

Though it *could* be a libgd version issue -- py_gd works with 2.3.2. (I
just tested that) not sure how back it goes -- we should probably do a
check when it builds. BUt it likely requires at least 2.3

**Comment by ChrisBarker-NOAA** [comment]
From that error:

py_gd.cpython-36m-x86_64-linux-gnu.so: undefined symbol: gdImageBmp

I'm guessing it's not finding libgd: I'm pretty sure that symbol has been there for a LONG time.
