### ISSUE TITLE
Some error messages while trying to install PyGnome!

### ISSUE THREAD

**Issue by chimin64** [NOAA-ORR-ERD/PyGnome#104]
Dear all,

I used "python 3.7" & "Conda python=3.8" to install PyGnome.
I downloaded and installed the Pygnome. Then, I receive the error messages when I executed the "pytest".

This is the error I receive on Ubuntu 18.04.3:
========================================================================
platform linux -- Python 3.7.10, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/chimin/GNOME/PyGnome/py_gnome
plugins: cov-3.0.0, timeout-2.0.1
collected 1344 items / 1 error / 1343 selected

==================================== ERRORS ====================================
______ ERROR collecting tests/unit_tests/test_environment/test_gridcur.py ______
../../../anaconda3/envs/gnomep38/lib/python3.7/site-packages/_pytest/python.py:578: in _importtestmodule
    mod = import_path(self.fspath, mode=importmode)
../../../anaconda3/envs/gnomep38/lib/python3.7/site-packages/_pytest/pathlib.py:524: in import_path
    importlib.import_module(module_name)
../../../anaconda3/envs/gnomep38/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1006: in _gcd_import
    ???
<frozen importlib._bootstrap>:983: in _find_and_load
    ???
<frozen importlib._bootstrap>:967: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:677: in _load_unlocked
    ???
../../../anaconda3/envs/gnomep38/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:161: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
../../../anaconda3/envs/gnomep38/lib/python3.7/site-packages/_pytest/assertion/rewrite.py:354: in _rewrite_test
    tree = ast.parse(source, filename=fn_)
../../../anaconda3/envs/gnomep38/lib/python3.7/ast.py:35: in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
E     File "<fstring>", line 1
E       (result=)
E              ^
E   SyntaxError: invalid syntax
=============================== warnings summary ===============================
../../../anaconda3/envs/gnomep38/lib/python3.7/site-packages/unit_conversion/__init__.py:32
  /home/chimin/anaconda3/envs/gnomep38/lib/python3.7/site-packages/unit_conversion/__init__.py:32: DeprecationWarning: The unit_conversion module is deprecated -- import as `nucos` instead
    "The unit_conversion module is deprecated -- "

../../../anaconda3/envs/gnomep38/lib/python3.7/site-packages/pyGnome-1.1.0-py3.7-linux-x86_64.egg/gnome/__init__.py:50
  /home/chimin/anaconda3/envs/gnomep38/lib/python3.7/site-packages/pyGnome-1.1.0-py3.7-linux-x86_64.egg/gnome/__init__.py:50: UserWarning: ERROR: The adios_db package, version >= 0.6.0 needs to be installed
    warnings.warn(msg)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
ERROR tests/unit_tests/test_environment/test_gridcur.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
========================= 2 warnings, 1 error in 6.00s ============================

Looking forward to hearing from you about what to do with these errors.

Regards,
 
Chimin

 Chi-Min Chiu (Ph.D)
 Coastal Ocean Monitoring Cente / National Cheng Kung University (NCKU) / Taiwan
 Email: chimin64@gmail.com

**Comment by ChrisBarker-NOAA** [comment]
PyGNOME requires Python 3.8 or better -- update Python, and the PyGNOME code, and try again.
