### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by Rgm1102** [NOAA-ORR-ERD/PyGnome#106]
Hello,

I was trying to install py_gnome with Anaconda, and everything goes well until the last testing (below the code that I used):

(gnome) C:\Users\Samsung\PyGnome\py_gnome\tests\unit_tests>py.test
ImportError while loading conftest 'C:\Users\Samsung\PyGnome\py_gnome\tests\conftest.py'.
..\conftest.py:15: in <module>
    from gnome.utilities import rand
E   ModuleNotFoundError: No module named 'gnome'

What would be a possible solution for that? ( it is written on my anaconda prompt), and I am using windows.

thank you!

**Comment by PrasadSJ** [comment]
Hello Peers, 

I am also getitng such errors as follows:

(gnome) C:\Users\SJ Prasad\PyGnome\py_gnome\tests\unit_tests>py.test
ImportError while loading conftest 'C:\Users\SJ Prasad\PyGnome\py_gnome\tests\conftest.py'.
..\conftest.py:15: in <module>
    from gnome.utilities import rand
E   ModuleNotFoundError: No module named 'gnome'

(gnome) C:\Users\SJ Prasad\PyGnome>python setup.py develop
python: can't open file 'setup.py': [Errno 2] No such file or directory

later i tried by entering from py_gnome folder, but still i am getitng error

(gnome) C:\Users\SJ Prasad\PyGnome\py_gnome>python setup.py develop
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
setting up cython extensions
running develop
D:\anaconda\envs\gnome\lib\site-packages\setuptools\command\easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\anaconda\envs\gnome\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing pyGnome.egg-info\PKG-INFO
D:\anaconda\envs\gnome\lib\site-packages\setuptools\dist.py:154: UserWarning: newlines not allowed and will break in the future
  warnings.warn("newlines not allowed and will break in the future")
writing dependency_links to pyGnome.egg-info\dependency_links.txt
writing top-level names to pyGnome.egg-info\top_level.txt
reading manifest file 'pyGnome.egg-info\SOURCES.txt'
running build_ext
skipping 'gnome\cy_gnome\cy_basic_types.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_mover.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_helpers.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_wind_mover.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_current_mover.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_cats_mover.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_component_mover.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_gridcurrent_mover.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_gridwind_mover.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_ice_mover.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_ice_wind_mover.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_currentcycle_mover.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_ossm_time.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_random_mover.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_random_mover_3d.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_rise_velocity_mover.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_land_check.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_grid_map.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_shio_time.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_grid.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_grid_rect.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_grid_curv.cpp' Cython extension (up-to-date)
skipping 'gnome/cy_gnome\cy_weatherers.cpp' Cython extension (up-to-date)
skipping 'gnome\utilities\geometry\cy_point_in_polygon.c' Cython extension (up-to-date)
building 'gnome.cy_gnome.cy_basic_types' extension
CATSMover_c.cpp
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\cstdlib(12): fatal error C1083: Cannot open include file: 'math.h': No such file or directory
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2


Could anyone suggest on this

Thanks

**Comment by jay-hennen** [comment]
> C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include\cstdlib(12): fatal error C1083: Cannot open include file: 'math.h': No such file or directory

Generally this sort of error during setup means you are missing a library of some sort. Unfortunately I can't identify which one it might be. If you use the Visual Studio Build Tools Installer make sure you have a Windows SDK and MSVC Runtimes installed.

If you have these installed, you may not have them on your command line path.  You should run the `vcvarsall.bat` or `vcvars64.bat` scripts that came with Visual Studio and then run the `python setup.py develop` in the produced command prompt. This is because those scripts set up a command line environment with the installed Visual C libraries and Windows SDKs in the correct path variables.

**Comment by ChrisBarker-NOAA** [comment]
It's a bit hard to keep up with all the changes in the MS compilers, etc, but a couple suggestions:

1) try bulding a really simple C extension first, if your system isn't set up to do that, it won't be able to build PyGNOME. Here's a tutorial on that:

https://tutorialedge.net/python/python-c-extensions-tutorial/

2) I *think* that the MS compiler install comes with a preconfigured command window:

https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#developer_command_prompt_shortcuts

If you find the right pre-configured command prompt -- then PyGNOME should build.

**Comment by ChrisBarker-NOAA** [comment]
NOTE: we have discovered a bug in our build scripts with the lastest version of setuptools. Options:

install an older setuptools:

`conda install "setuptools<=58"`

Or wait for a fix -- coming soon.

**Comment by ChrisBarker-NOAA** [comment]
Now fixed in f5266ecece9.

Make sure you have the latest setuptools
