### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by lindbergh153** [NOAA-ORR-ERD/PyGnome#109]
I tried to install the package following the instruction and the problem is attached below.

============================================================================
(gnome) C:\Users\umroot\Desktop\PyGnome-master\py_gnome>python setup.py develop
Traceback (most recent call last):
  File "D:\Miniconda3\envs\gnome\lib\site-packages\git\__init__.py", line 87, in <module>
    refresh()
  File "D:\Miniconda3\envs\gnome\lib\site-packages\git\__init__.py", line 76, in refresh
    if not Git.refresh(path=path):
  File "D:\Miniconda3\envs\gnome\lib\site-packages\git\cmd.py", line 341, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    from git import Repo
  File "D:\Miniconda3\envs\gnome\lib\site-packages\git\__init__.py", line 89, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc)) from exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

**Comment by ChrisBarker-NOAA** [comment]
Sorry -- as PyGNOME is under active development, we are using git tagging in our installation.

So you need to have a command line git client installed in order for this to work.

There are many options, but this should work:

https://git-scm.com/download/win

We really should make that optional, but for now, installing git should work.

**Comment by ChrisBarker-NOAA** [comment]
Actually, now that I think about it -- if you don't need a system git for any other reason, you can install it with conda into your gnome enviroment:

`conda install git`

**Comment by lindbergh153** [comment]
> Actually, now that I think about it -- if you don't need a system git for any other reason, you can install it with conda into your gnome enviroment:
> 
> `conda install git`
Thanks for your help. Another problem is attached below.
===============================================================================
LINK : fatal error LNK1181: cannot open input file 'build\temp.win-amd64-3.8\Release\gnome\cy_gnome\cy_basic_types.cp38-win_amd64.lib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181

**Comment by ChrisBarker-NOAA** [comment]
this is due to a change in setuptools -- for a quick fix, you can downgrade setuptools:


conda install "setuptools<=58"

We should have a fix soon

-CHB

**Comment by ChrisBarker-NOAA** [comment]
Now fixed in f5266ecece9.

Make sure you have the latest setuptools
