### ISSUE TITLE
py_gd problem

### ISSUE THREAD

**Issue by socolofs** [NOAA-ORR-ERD/PyGnome#114]
I recently updated py_gd and got the error:

"""
ImportError: dlopen(/opt/miniconda3/envs/tamoc3/lib/python3.9/site-packages/py_gd/py_gd.cpython-39-darwin.so, 2): Library not loaded: @rpath/libfontconfig.1.dylib
  Referenced from: /opt/miniconda3/envs/tamoc3/lib/libgd.3.dylib
  Reason: Incompatible library version: libgd.3.dylib requires version 14.0.0 or later, but libfontconfig.1.dylib provides version 13.0.0
"""

This is a conda or conda-forge problem.  For now, the fix is to force install of the compatible fontconfig package using:

"""
conda install fontconfig==2.13.1
"""

Thanks!

**Comment by ChrisBarker-NOAA** [comment]
Thanks for the report.

NOTE: This is for Mac OS-X -- probably not an issue on other platforms, but maybe ....

**Comment by ChrisBarker-NOAA** [comment]
I've updated the builds of py_gd -- so this should no longer be an issue.

However, It hasn't shown up in serach path yet for conda.

But if you install the latest py_gd from:

https://anaconda.org/conda-forge/py_gd/files

and conda update libgd

then it should work -- and hopefully, it will all work out of the box soon.

**Comment by ChrisBarker-NOAA** [comment]
Looks like it's working now :-)

**Comment by ChrisBarker-NOAA** [comment]
NOTE: to update an environment:

conda update py_gd libgd

should work -- or, better yet, rebuild it from scratch.
