### ISSUE TITLE
Problem with adding weatherers

### ISSUE THREAD

**Issue by lindbergh153** [NOAA-ORR-ERD/PyGnome#116]
Hello, I tried to add the weathering module into the blowout simulation but failed. The code and error message is enclosed below. 

code
============================================================================
start_time = datetime(2021, 10, 20, 12, 0)

model = gs.Model(start_time=start_time, duration=timedelta(days=2), time_step=60 * 15)

model.movers += gs.PyCurrentMover(fn_current)
model.movers += gs.PyWindMover(fn_wind)
model.movers += gs.RiseVelocityMover()
model.movers += gs.RandomMover3D(vertical_diffusion_coef_above_ml=0,
                                 vertical_diffusion_coef_below_ml=1,
                                 horizontal_diffusion_coef_above_ml=1e4)

ud = WeibullDistribution(alpha=1.8, max_=0.02940873, min_=0.00091055)

release_rate = 3000
units='bbl/day'
release_rate = uc.convert(units, "m^3/s", release_rate)
release_rate = release_rate * 880.3
amount = release_rate * timedelta(days=2).total_seconds()

spill = gs.subsurface_plume_spill(num_elements=8000,
                               start_position=(-49.67, 50.11, -800.0),
                               release_time=start_time,
                               distribution=ud,
                               distribution_type='droplet_size',
                               end_release_time=start_time + timedelta(days=2),
                               amount=amount,
                               substance='AD02170',
                               units='kg')
water = Water(300.15)
model.environment += water

wind = constant_wind(20., 117, 'knots')

waves = Waves(wind, water)
model.environment += waves

model.spills += spill
model.add_weathering(which='standard')

model.outputters += WeatheringOutput()
model.full_run()

error
============================================================================
Traceback (most recent call last):
  File "D:/PyOilSpill/integrated_model/testing_GNOME.py", line 62, in <module>
    model.full_run()
  File "d:\git_download\pygnome\py_gnome\gnome\model.py", line 1123, in full_run
    results = self.step()
  File "d:\git_download\pygnome\py_gnome\gnome\model.py", line 1048, in step
    self.weather_elements()
  File "d:\git_download\pygnome\py_gnome\gnome\model.py", line 927, in weather_elements
    w.weather_elements(sc, time_step, model_time)
  File "d:\git_download\pygnome\py_gnome\gnome\weatherers\spreading.py", line 470, in weather_elements
    data['age'][s_mask] + time_step)
  File "d:\git_download\pygnome\py_gnome\gnome\weatherers\spreading.py", line 298, in update_area2
    blob_init_volume[m_age][0])
  File "D:\Program Files\MiniANACONDA\lib\site-packages\backports\functools_lru_cache.py", line 149, in wrapper
    result = user_function(*args, **kwds)
  File "d:\git_download\pygnome\py_gnome\gnome\weatherers\spreading.py", line 90, in _gravity_spreading_t0
    relative_buoyancy)) ** (1. / 3)
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

Process finished with exit code 1

**Comment by lindbergh153** [comment]
I use the latest version 1.1.0. Even I input the substance using a JSON file, it still failed with the same error message.

oil=gs.GnomeOil(filename='hibernia_AD02170.json')
===============================================================================
Traceback (most recent call last):
  File "D:/OilSpillModel/testing_gnome.py", line 60, in <module>
    model.full_run()
  File "D:\Miniconda3\envs\gnome\lib\site-packages\gnome\model.py", line 1186, in full_run
    results = self.step()
  File "D:\Miniconda3\envs\gnome\lib\site-packages\gnome\model.py", line 1110, in step
    self.weather_elements()
  File "D:\Miniconda3\envs\gnome\lib\site-packages\gnome\model.py", line 989, in weather_elements
    w.weather_elements(sc, time_step, model_time)
  File "D:\Miniconda3\envs\gnome\lib\site-packages\gnome\weatherers\spreading.py", line 464, in weather_elements
    self.update_area2(water_kvis,
  File "D:\Miniconda3\envs\gnome\lib\site-packages\gnome\weatherers\spreading.py", line 294, in update_area2
    t0 = self._gravity_spreading_t0(water_viscosity,
  File "D:\Miniconda3\envs\gnome\lib\site-packages\gnome\weatherers\spreading.py", line 86, in _gravity_spreading_t0
    (blob_init_vol / (water_viscosity * constants.gravity *
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

**Comment by lindbergh153** [comment]
Thanks for your help. I enclosed the script and data through OneDrive link as below: https://1drv.ms/u/s!Amm7YlQZYzsdwjee6aHuNEkz8Qiy?e=4JSphC

**Comment by ChrisBarker-NOAA** [comment]
It looks like the script in there is only a TAMOC script -- not a PyGNOME one.

But in any case, I found the bug. If you pull the latest develop branch, your script should run.

However, we have not carefully tested oils being released subsurface, and then applying surface weathering -- so do see if the results make sense. IN particular, teh spreading algorithm assumes that it's a surface release to calculate the initial thickness -- so it may be odd in this case (that was the source of the bug).

It's not crashing now, but it may not be correct, either.

We'd appreciate any feedback on what you learn though.

Here's my version of your script:

```
import os
from datetime import datetime, timedelta
import nucos as uc

from gnome import scripting as gs

from gnome.utilities.distributions import WeibullDistribution, UniformDistribution

fn_current = "current_data2021.nc"
fn_wind = "wind_2021.nc"

start_time = datetime(2021, 10, 20, 12, 0)

model = gs.Model(start_time=start_time,
                 duration=gs.days(2),
                 time_step=60 * 15)

model.movers += gs.PyCurrentMover(fn_current)
model.movers += gs.PyWindMover(fn_wind)
model.movers += gs.RiseVelocityMover()
model.movers += gs.RandomMover3D(vertical_diffusion_coef_above_ml=0,
                                 vertical_diffusion_coef_below_ml=1,
                                 horizontal_diffusion_coef_above_ml=1e4)

ud = WeibullDistribution(alpha=1.8, max_=0.02940873, min_=0.00091055)

release_rate = 3000
units='bbl/day'
release_rate = uc.convert(units, "m^3/s", release_rate)
release_rate = release_rate * 880.3
amount = release_rate * timedelta(days=2).total_seconds()

spill = gs.subsurface_plume_spill(
    num_elements=8000,
    start_position=(-49.67, 50.11, -800.0),
    release_time=start_time,
    distribution=ud,
    distribution_type='droplet_size',
    end_release_time=start_time + timedelta(days=2),
    amount=amount,
    substance=gs.GnomeOil(filename='hibernia_AD02170.json'),
    units='kg')

water = gs.Water(300.15)
model.environment += water

wind = gs.constant_wind(20., 117, 'knots')

waves = gs.Waves(wind, water)
model.environment += waves

model.spills += spill
model.add_weathering(which='standard')

model.outputters += gs.OilBudgetOutput()
model.outputters += gs.WeatheringOutput(output_dir="weathering_data")

model.full_run()

```

**Comment by lindbergh153** [comment]
I'm not sure whether my version is the latest one (installed last month), but it still doesn't work for the script you gave.

![image](https://user-images.githubusercontent.com/76455688/161156958-8fee320a-396d-4b16-b4da-f5f57434453f.png)

**Comment by ChrisBarker-NOAA** [comment]
It's not -- I literally made a change yesterday.

You need to download the version from the "develop" branch on github. The best way to do that is to close the git repo:

```
git clone https://github.com/NOAA-ORR-ERD/PyGnome.git
cd PyGnome
git checkout develop
git pull
```

And then you'll have the latest code.

Once you've done this, you can do `git pull` in the future to get the latest.

-CHB

**Comment by lindbergh153** [comment]
After these procedures, do I need to reinstall the newly downloaded package again?
![image](https://user-images.githubusercontent.com/76455688/161356176-b452692e-9a7b-4267-b8fb-8c282e94707e.png)

**Comment by ChrisBarker-NOAA** [comment]
yes -- you do need to re-install. When working with the git source, it's often easier to install in "develop" mode:

python setup.py develop

or you can re-install:

python setup.py install

The advantage of "develop" mode is that if you update the source code again (git pull, or editing it directly yourself) it will not need to be re-installed unless the C++ code has changed, which is not often.
