### ISSUE TITLE
Problem with PyGnome compilation (LNK1181)

### ISSUE THREAD

**Issue by rsbragio** [NOAA-ORR-ERD/PyGnome#117]
Hi, I tried to install PyGnome and I had the following error:
LINK : fatal error LNK1181: cannot open input file 'build\temp.win-amd64-3.8\lib_gnome\cy_basic_types.cp38-win_amd64.lib'
I checked the file and it exists in the directory. However, PyGnome is not compilling.
I appretiate if anyone can help with this issue.
Thanks

**Comment by rsbragio** [comment]
Thanks very much. 
I was able to compile the code with command  python setup.py install and it is running ok.
However, it did not seem to work well with command python setup.py develop.
Best regards

**Comment by ChrisBarker-NOAA** [comment]
hmm, odd. Did you try running:

`setup.py cleanall`

first?

Glad you got it running -- and thanks for the report, we need to modernize the build soon, so hopefully this will all work better soon.
