### ISSUE TITLE
gridded package >= 0.3.0

### ISSUE THREAD

**Issue by odilonrf** [NOAA-ORR-ERD/PyGnome#125]
Hello all,

I am trying to run a python code in Spyder within the gnome environment, but the following error messages shows up:

*******************************************************************************************************************************
runfile('C:/Windows/System32/PyGnome-1.0.0/vs_projects/Run_PyGnome.py', wdir='C:/Windows/System32/PyGnome-1.0.0/vs_projects')
C:\ProgramData\Anaconda3\envs\gnome\lib\site-packages\pygnome-1.0.0-py3.8-win-amd64.egg\gnome\__init__.py:49: UserWarning: ERROR: The gridded package, version >= 0.3.0 needs to be installed
  warnings.warn(msg)
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\gnome\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\windows\system32\pygnome-1.0.0\vs_projects\run_pygnome.py", line 9, in <module>
    import gnome.scripting as gs

  File "C:\ProgramData\Anaconda3\envs\gnome\lib\site-packages\pygnome-1.0.0-py3.8-win-amd64.egg\gnome\__init__.py", line 119, in <module>
    from . import (environment,

  File "C:\ProgramData\Anaconda3\envs\gnome\lib\site-packages\pygnome-1.0.0-py3.8-win-amd64.egg\gnome\environment\__init__.py", line 9, in <module>
    from .environment import Environment, env_from_netCDF, ice_env_from_netCDF

  File "C:\ProgramData\Anaconda3\envs\gnome\lib\site-packages\pygnome-1.0.0-py3.8-win-amd64.egg\gnome\environment\environment.py", line 25, in <module>
    from gnome.persist import base_schema

  File "C:\ProgramData\Anaconda3\envs\gnome\lib\site-packages\pygnome-1.0.0-py3.8-win-amd64.egg\gnome\persist\__init__.py", line 10, in <module>
    from gnome.persist import base_schema, extend_colander, validators

  File "C:\ProgramData\Anaconda3\envs\gnome\lib\site-packages\pygnome-1.0.0-py3.8-win-amd64.egg\gnome\persist\base_schema.py", line 22, in <module>
    from .extend_colander import NumpyFixedLenSchema

  File "C:\ProgramData\Anaconda3\envs\gnome\lib\site-packages\pygnome-1.0.0-py3.8-win-amd64.egg\gnome\persist\extend_colander.py", line 19, in <module>
    import gnome.basic_types

  File "C:\ProgramData\Anaconda3\envs\gnome\lib\site-packages\pygnome-1.0.0-py3.8-win-amd64.egg\gnome\basic_types.py", line 24, in <module>
    from .cy_gnome import cy_basic_types as cbt

ImportError: DLL load failed while importing cy_basic_types: Não foi possível encontrar o procedimento especificado.
*******************************************************************************************************************************
One question is about the gridded package. It seems it is not installed. However, it is! I just installed it and such error persists. I do not know how to solve it.

The second point is about the absent DLL file. Which file should be absent?

Many thanks for your help,
Odilon.

**Comment by ChrisBarker-NOAA** [comment]
The gridded package warning and the DLL issue are independent.

For gridded:
- make sure Spyder is using the environment gnome is installed into.
-  check which gridded package is installed into that conda environment:
-  `conda` list (or `conda list gridded`)

For the dll issue. This means pyGNOME was not built / installed properly.

1) make sure you have the latest, both of pygnome and setuptools (in conda)

Both the master and develop branch should work, but if master isn't, try develop.

NOTE: master will only build with setuptools < 62, develop should build with the latest setuptools. Check your version with:

conda list setuptools


Check the error messages when you built it (e.g. the setup.py develop (or install) )
Sorry that there are lots of warnings, but look carefully if there are any actual errors.

Make sure to do a clean build: run `python setup.py cleanall` before rebuilding.

It might help to do just a build first, before the install:

python setup.py build

If it still build error-free but won't run -- capture the output and post here again.

**Comment by odilonrf** [comment]
Hello Cris,

Thank you very much for your reply.

I followed your directions and it does not work. I tried to reinstall again the updated PyGnome with no errors. But, when I run my script, the same errors below occur.
I run all time in the gnome environment. I checked the gridded version and it is exactly the same varsion requested: 0.3.0. I checked the setuptools, whose version is 62.6.0. I used develop instead of master.

Below are the error messages:

******************************************************************************************************************************
c:\pygnome\pygnome_new\pygnome-master\py_gnome\gnome\__init__.py:62: UserWarning: ERROR: The gridded package, version >= 0.3.0 needs to be installed: 
  warnings.warn(msg)
Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\gnome\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\windows\system32\pygnome-1.0.0\vs_projects\run_pygnome.py", line 9, in <module>
    import gnome.scripting as gs

  File "c:\pygnome\pygnome_new\pygnome-master\py_gnome\gnome\__init__.py", line 136, in <module>
    from . import (environment,

  File "c:\pygnome\pygnome_new\pygnome-master\py_gnome\gnome\environment\__init__.py", line 5, in <module>
    from .environment import Environment, env_from_netCDF, ice_env_from_netCDF

  File "c:\pygnome\pygnome_new\pygnome-master\py_gnome\gnome\environment\environment.py", line 17, in <module>
    from gnome.persist import base_schema

  File "c:\pygnome\pygnome_new\pygnome-master\py_gnome\gnome\persist\__init__.py", line 19, in <module>
    from .extend_colander import (TupleSchema, SequenceSchema, SchemaNode,

  File "c:\pygnome\pygnome_new\pygnome-master\py_gnome\gnome\persist\extend_colander.py", line 14, in <module>
    import gnome.basic_types

  File "c:\pygnome\pygnome_new\pygnome-master\py_gnome\gnome\basic_types.py", line 24, in <module>
    from .cy_gnome import cy_basic_types as cbt

ImportError: DLL load failed while importing cy_basic_types: Não foi possível encontrar o procedimento especificado.
******************************************************************************************************************************


I do not know if it will help, but after the reinstallation of PyGnome, I tested it following the NOAA directions and some other errors raised up:


******************************************************************************************************************************
========================================== short test summary info ===========================================
FAILED test_grids.py::test_grid_wind_rect - TypeError: '<' not supported between instances of 'numpy.longdou...
FAILED test_ucode_filenames.py::test_ucode_char_in_grid_mover_filename[mover_test0] - OSError: GridCurrentMo...
FAILED test_ucode_filenames.py::test_ucode_char_in_grid_mover_filename[mover_test1] - OSError: GridWindMover...
FAILED test_ucode_filenames.py::test_ucode_char_in_grid_mover_filename[mover_test2] - OSError: GridCurrentMo...
FAILED test_cy\test_cy_grids.py::test_grid_wind_rect - TypeError: '<' not supported between instances of 'nu...
FAILED test_environment\test_filegridcurrent.py::test_gridcur_in_model - PermissionError: [WinError 32] O ar...
FAILED test_environment\test_gridcur.py::test_in_model - PermissionError: [WinError 32] O arquivo já está se...
FAILED test_outputters\test_netcdf_outputter.py::test_read_standard_arrays[1-True] - TypeError: '<' not supp...
FAILED test_outputters\test_netcdf_outputter.py::test_read_standard_arrays[1-False] - TypeError: '<' not sup...
FAILED test_outputters\test_netcdf_outputter.py::test_read_standard_arrays[2.4-True] - TypeError: '<' not su...
FAILED test_outputters\test_netcdf_outputter.py::test_read_standard_arrays[2.4-False] - TypeError: '<' not s...
FAILED test_outputters\test_netcdf_outputter.py::test_read_standard_arrays[3-True] - TypeError: '<' not supp...
FAILED test_outputters\test_netcdf_outputter.py::test_read_standard_arrays[3-False] - TypeError: '<' not sup...
FAILED test_outputters\test_netcdf_outputter.py::test_read_all_arrays - TypeError: '<' not supported between...
FAILED test_outputters\test_netcdf_outputter.py::test_write_output_post_run[1] - TypeError: '<' not supporte...
FAILED test_outputters\test_netcdf_outputter.py::test_write_output_post_run[2] - TypeError: '<' not supporte...
FAILED test_outputters\test_renderer.py::test_animation_in_model - PermissionError: [WinError 32] O arquivo ...
======== 17 failed, 1271 passed, 59 skipped, 23 xfailed, 2 xpassed, 74 warnings in 555.86s (0:09:15) =========
Error opening NetCDF fileError opening NetCDF fileError opening NetCDF file
******************************************************************************************************************************

So, I am wondering if you could give some hint to solve it because I am having no ideas.

Many thanks,
Odilon.
