### ISSUE TITLE
version of Oil object

### ISSUE THREAD

**Issue by larissafranklin23** [NOAA-ORR-ERD/PyGnome#133]
How could I fix it?
![image](https://user-images.githubusercontent.com/66744674/196151103-cecbde2f-987a-4880-b9e3-b32e9a3afd68.png)

**Comment by coconnor8** [comment]
The version of the adios_db does not match the version that was used to create your oil.The oil's version is in the field adios_data_model_version . If that is '0.12.0' you need to update adios_db. Otherwise get a new copy of the oil.

**Comment by larissafranklin23** [comment]
Keep getting the same error. I tried to reinstall the adios_db with the zip in the main page of ADIOS. 
I also tried to get a new copy of the oil and I'm getting the same problem. 

![image](https://user-images.githubusercontent.com/66744674/198120618-d529b773-8f77-42fe-8cd4-44baca1cde2d.png)

**Comment by ChrisBarker-NOAA** [comment]
Somehow you still have an old(er) version of the adios_db package.

You want the production branch from here:

https://github.com/NOAA-ORR-ERD/adios_oil_database

which is version 1.0.2

But the last release on gitHub is 1.0.1, which should also work. But you are running 1.0.0b1

I'll make a new release now, but somehow your update didn't take.

You can also check the actual version running with:

python -c "import adios_db; print(adios_db.__version__)"

-CHB

**Comment by larissafranklin23** [comment]
Now I have the actual version of adios_db but I'm still getting the same error. 
I also checked my PyGnome version and everything seems to be ok. 
![image](https://user-images.githubusercontent.com/66744674/198181786-fa8e199b-4f2b-4444-9229-27305ac3c232.png)

**Comment by ChrisBarker-NOAA** [comment]
look at your output -- you still have adios_db version 1.0.0b1 -- not 1.0.2

https://github.com/NOAA-ORR-ERD/adios_oil_database/releases/tag/v1.0.2

**Comment by larissafranklin23** [comment]
Now I solve the problem of the adios version, thank you.
But now I'm facing another problem. When I use gas-oil-exxon_AD00458 my model runs ok but when I try to use other oils from the adios database, this is the message that appears to me. 

Do you know how can I fix it?
![image](https://user-images.githubusercontent.com/66744674/198271534-41ca2764-6927-43e7-86b2-4611bdfeecd2.png)

**Comment by ChrisBarker-NOAA** [comment]
This is a bug that was fixed recently -- make sure to use the latest "production" branch.
