### ISSUE TITLE
Hindcast trajectory & Data assimilation

### ISSUE THREAD

**Issue by tommasogallingani** [NOAA-ORR-ERD/PyGnome#137]
Hi, 
we were wondering is **hindcast trajectory** for data assimilation is already implemend and tested in PyGnome.
There's only few information about it in the repo documentation in the step function associated with model. 
We have the same question also for data assimilation procedure that does not seems to be implemeneted.
Thanks a lot
Tommaso

`    def step(self):
        '''
        Steps the model forward (or backward) in time. Needs testing for
        hindcasting.
        '''`

**Comment by ChrisBarker-NOAA** [comment]
Running the model backwards ias been on the list for along time -- but we haven't had a chance to get around to implementing it. For at least the basic "movers", it should be pretty straightforward and may "just work" -- but there will need to be a fair bit of testing, and fixing of edge cases.

First step would be to set a negative timestep, ans see what happens :-)
