### ISSUE TITLE
Buffer has wrong number of dimensions (expected 1, got 2)

### ISSUE THREAD

**Issue by larissafranklin23** [NOAA-ORR-ERD/PyGnome#138]
I was using the gas-oil-exxon_AD00458 when I changed it to boscan-amoco AH00171, it started to show this error message.

![image](https://user-images.githubusercontent.com/66744674/201914302-1e4837fe-15b9-4e8a-8f1e-10ad109195bc.png)

**Comment by ChrisBarker-NOAA** [comment]
This should be all fixed now, in the main and production branches.
