### ISSUE TITLE
PyGnome license

### ISSUE THREAD

**Issue by tommasogallingani** [NOAA-ORR-ERD/PyGnome#140]
Hi all,
I was wondering under which license this library is distributed.
I've seen that for others librerary of NOAA the license is reported. 
e.g. https://github.com/NOAA-ORR-ERD/post_gnome/blob/main/LICENSE.txt

Thanks a lot
Tommaso

**Comment by ChrisBarker-NOAA** [comment]
It is in in public domain, same as the LICENSE file you found in the post_gnome project.

Thanks for asking -- we have now added a LICENSE file to the PyGNOME project as well -- it should now be in the main branch.

**Comment by tommasogallingani** [comment]
Thanks @ChrisBarker-NOAA
