### ISSUE TITLE
Input data format | NETCdf

### ISSUE THREAD

**Issue by tommasogallingani** [NOAA-ORR-ERD/PyGnome#141]
Hi all,

we were wondering if there are guidelines regarding the structure and naming convention for input file (e.g. NetCDF for currents).

We are for example wondering how lat/long, current direction and depth values are found and processed before model evaluation.

As an example, we were wondering if data from Copernicus database
https://data.marine.copernicus.eu/login?redirect=%2Fproduct%2FGLOBAL_ANALYSISFORECAST_PHY_001_024%2Fdownload%3Fdataset%3Dcmems_mod_glo_phy-cur_anfc_0.083deg_PT6H-i

have the correct naming convention and how we can be sure the processing is done correctly by the ingestion pipeline.

Thanks a lot
[med-cmcc-cur-an-fc-qm_1667901189222.zip](https://github.com/NOAA-ORR-ERD/PyGnome/files/10724901/med-cmcc-cur-an-fc-qm_1667901189222.zip)

Tommaso

**Comment by tommasogallingani** [comment]
I've found a nice file with mapping of all variables in the repository. For anyone interest in that I'll paste the code below and close the issue

`"""
Module that provides the names used when processing netcdf files

Each type of Environment object has a set of names that it uses
to determine what the contents of a netcdf file are.

**cf_names:**

These are "standard names", as defined by the CF metadata standard:

https://cfconventions.org/standard-names.html

These are the best options to use, as the are standardized. When loading a netcdf file, the Environment
objects will first look for variable with cf_names, to identify their meaning. If no
variables exist with the standard names, then common variable names will be used.

**nc_names:**

These are common variable names used for the variables PyGNOME uses. If you set the variable names in
a netcdf files to one these names, PYGNOME should be able to load the file.

**Name Mapping:**


**grid_temperature**

  Default Names: water_t,temp

  CF Standard Names: sea_water_temperature,sea_surface_temperature

**grid_salinity**

  Default Names: salt

  CF Standard Names: sea_water_salinity,sea_surface_salinity

**grid_sediment**

  Default Names: sand_06

  CF Standard Names:

**ice_concentration**

  Default Names: ice_fraction,aice

  CF Standard Names: sea_ice_area_fraction

**bathymetry**

  Default Names: h

  CF Standard Names: depth

**grid_current**

  Default Names: u,v,w

  CF Standard Names: u,v,w

**grid_wind**

  Default Names: u,v

  CF Standard Names: u,v

**ice_velocity**

  Default Names: u,v

  CF Standard Names: u,v

"""

nc_names = {
    'grid_temperature': {
        'default_names': ['water_t', 'temp'],
        'cf_names': ['sea_water_temperature', 'sea_surface_temperature']
    },
    'grid_salinity': {
        'default_names': ['salt'],
        'cf_names': ['sea_water_salinity', 'sea_surface_salinity']
    },
    'grid_sediment': {
        'default_names': ['sand_06'],
        'cf_names': []
    },
    'ice_concentration': {
        'default_names': ['ice_fraction', 'aice'],
        'cf_names': ['sea_ice_area_fraction']
    },
    'bathymetry': {
        'default_names': ['h'],
        'cf_names': ['depth']
    },
    'grid_current': {
        'default_names': {
            'u': ['u', 'U', 'water_u', 'curr_ucmp', 'u_surface', 'u_sur'],
            'v': ['v', 'V', 'water_v', 'curr_vcmp', 'v_surface', 'v_sur'],
            'w': ['w', 'W']
        },
        'cf_names': {
            'u': [
                'eastward_sea_water_velocity',
                'surface_eastward_sea_water_velocity'
            ],
            'v': [
                'northward_sea_water_velocity',
                'surface_northward_sea_water_velocity'
            ],
            'w': ['upward_sea_water_velocity']
        }
    },
    'grid_wind': {
        'default_names': {
            'u': ['air_u', 'Air_U', 'air_ucmp', 'wind_u','u-component_of_wind_height_above_ground' ],
            'v': ['air_v', 'Air_V', 'air_vcmp', 'wind_v','v-component_of_wind_height_above_ground']
        },
        'cf_names': {
            'u': ['eastward_wind', 'eastward wind'],
            'v': ['northward_wind', 'northward wind']
        }
    },
    'ice_velocity': {
        'default_names': {
            'u': ['ice_u', 'uice'],
            'v': ['ice_v', 'vice']
        },
        'cf_names': {
            'u': ['eastward_sea_ice_velocity'],
            'v': ['northward_sea_ice_velocity']
        }
    },
}`

**Comment by ChrisBarker-NOAA** [comment]
nice find -- sorry we didn't let you know -- a while back we had moved all that to one file. That is also now extracted and included in the documentation -- though I don't think that version of the docs has been published yet :-(

BTW: if you find a "compliant" file that doesn't load, let us know. And we could potentially add a name or two to match a commonly used model's output as well.
