### ISSUE TITLE
Simulate spill over a moving source

### ISSUE THREAD

**Issue by larissafranklin23** [NOAA-ORR-ERD/PyGnome#143]
Hello, 
I was running my model with a fixed spill source but now I need to make some changes to simulate spill over a moving source.
For this, I have the average travel speed, the course of the ship and a starting latitude and longitude point. How can I make this insertion in the script?
I was doing this, but it's not exactly what I need.
![image](https://user-images.githubusercontent.com/66744674/227718876-13495d68-6473-4e30-94ea-bc06ac6f3d15.png)

**Comment by ChrisBarker-NOAA** [comment]
In the future, try to post code as text, rather than an image -- it's easier to read.

you can surround it with tripple backticks(``` code ```) to make it format right (or click the <> button on the toolbar.

Anyway, your are doing the right thing, except:

![image](https://user-images.githubusercontent.com/916576/227734915-2dc8cf87-4037-4ca6-ac30-94b9aed4f0b2.png)

There's a comma, rather than a decimal in the end_position:

This sets the latitude to 7, and the depth to 30 -- the surface release should ignore the depth, but you won't get the fight latitude!

**Comment by larissafranklin23** [comment]
Hello, I was trying to work with PyGnome yesterday and I was getting this same message error. I changed my time step and it worked, I think the model was blowing up. But now I'm trying to do the same thing for a spill with another characteristics, same ERA5 and Mercator data, and it's not working. 


Inicializando o modelo
Adicionando Mapa
Adicionando o Derramamento
Adicionando RandomMover:
Adicionando Grid wind:
Adicionando Current mover:
Adicionando Outputters
removed C:\PyGnome-main\py_gnome\scripts\testing_scripts\script_2019\AFRAMAX\Castro_Alves\script_ex_saida.nc
removed C:\PyGnome-main\py_gnome\scripts\testing_scripts\script_2019\AFRAMAX\Castro_Alves\script_ex_saida.nc
doing full run
Note: Images folder and animation do not create same output, for demonstration
step: 0000 -- memuse: 108.082031MB
c:\pygnome-main\py_gnome\gnome\environment\gridded_objects_base.py:622: UserWarning: Variable0 units is not supported: m s**-1Using them unconverted as m/s
  warnings.warn("{0} units is not supported: {1}"
step: 0001 -- memuse: 123.441406MB
step: 0002 -- memuse: 125.718750MB
c:\pygnome-main\py_gnome\gnome\weatherers\spreading.py:833: RuntimeWarning: divide by zero encountered in divide
  frac_cov = (v_max ** 2 *
step: 0003 -- memuse: 127.027344MB
step: 0004 -- memuse: 128.000000MB
step: 0005 -- memuse: 129.246094MB
step: 0006 -- memuse: 129.726562MB
step: 0007 -- memuse: 131.273438MB
step: 0008 -- memuse: 132.398438MB
step: 0009 -- memuse: 132.316406MB
step: 0010 -- memuse: 132.058594MB
step: 0011 -- memuse: 132.871094MB
step: 0012 -- memuse: 134.257812MB
step: 0013 -- memuse: 134.406250MB
step: 0014 -- memuse: 135.113281MB
step: 0015 -- memuse: 136.269531MB
step: 0016 -- memuse: 136.570312MB
step: 0017 -- memuse: 137.140625MB
step: 0018 -- memuse: 138.136719MB
step: 0019 -- memuse: 139.328125MB
step: 0020 -- memuse: 139.761719MB
step: 0021 -- memuse: 140.371094MB
step: 0022 -- memuse: 142.066406MB
step: 0023 -- memuse: 141.882812MB
step: 0024 -- memuse: 143.527344MB
step: 0025 -- memuse: 143.460938MB
step: 0026 -- memuse: 144.929688MB
step: 0027 -- memuse: 145.765625MB
step: 0028 -- memuse: 146.289062MB
step: 0029 -- memuse: 146.953125MB
step: 0030 -- memuse: 147.312500MB
step: 0031 -- memuse: 148.453125MB
step: 0032 -- memuse: 149.941406MB
step: 0033 -- memuse: 150.171875MB
step: 0034 -- memuse: 150.597656MB
step: 0035 -- memuse: 151.808594MB
Traceback (most recent call last):
  File "C:\Anaconda\envs\gnome\lib\site-packages\shapefile.py", line 2329, in __dbfRecord
    value = int(value)
ValueError: cannot convert float NaN to integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PyGnome-main\py_gnome\scripts\testing_scripts\script_2019\AFRAMAX\Castro_Alves\aframax_castroalves.py", line 204, in <module>
    for step in model:
  File "c:\pygnome-main\py_gnome\gnome\model.py", line 1206, in __next__
    return self.step()
  File "c:\pygnome-main\py_gnome\gnome\model.py", line 1136, in step
    output_info = self.output_step(isValid)
  File "c:\pygnome-main\py_gnome\gnome\model.py", line 1141, in output_step
    output_info = self.write_output(isvalid)
  File "c:\pygnome-main\py_gnome\gnome\model.py", line 1064, in write_output
    output = outputter.write_output(self.current_time_step)
  File "c:\pygnome-main\py_gnome\gnome\outputters\shape.py", line 153, in write_output
    self._record_shape_entries(sc)
  File "c:\pygnome-main\py_gnome\gnome\outputters\shape.py", line 188, in _record_shape_entries
    writer.record(curr_time.strftime('%Y-%m-%dT%H:%M:%S'),
  File "C:\Anaconda\envs\gnome\lib\site-packages\shapefile.py", line 2300, in record
    self.__dbfRecord(record)
  File "C:\Anaconda\envs\gnome\lib\site-packages\shapefile.py", line 2332, in __dbfRecord
    value = int(float(value))
ValueError: cannot convert float NaN to integer

**Comment by ChrisBarker-NOAA** [comment]
It will be tricky to figure this out without you input data -- is it possible for you to put the nc files you are using somewhere we can download them? And your script, of course.

A few notes in the meantime:

the lines: `step: 0027 -- memuse: 145.765625MB` come from a line like this:

```
        print("step: %.4i -- memuse: %fMB" % (step['step_num'],
                                              utilities.get_mem_use()))
```
That is for debugging, in case you are having memory issues -- you can remove it to keep your output cleaner.

The final error is that a value is NaN (not a number) when trying to write the shapefile output. It might be helpful to turn off the shapefile output and make sure it runs, and if possible look at the result with the netcdf output.

Where the NaN come from is the key question -- it may be a result of an error in your input files, or it may be a big in our code -- one hint is:

```
c:\pygnome-main\py_gnome\gnome\weatherers\spreading.py:833: RuntimeWarning: divide by zero encountered in divide
frac_cov = (v_max ** 2 *
```

We have recently been updating the spreading code -- I think this may have been fixed.

Please give the latest "main" branch a try, and if that has similar issues, post here again.
