### ISSUE TITLE
Weathering output and amount (units)

### ISSUE THREAD

**Issue by francielleholtz** [NOAA-ORR-ERD/PyGnome#146]
Hey! I was checking my outputs and I got to my netCDF file, and I got a question. I'm using the AD01688 oil in a surface_point_line_spill in a continuous 30 days spill.
In mass_balance, it says that all the variables are in kg, but viscosity (m^2/s) and density (kg/m^3). I'm confused because:

1. Is it possible for me to change from kg to bbl or m^3, so my output is in the unit I need, or do I need to do it after?

2. In:  
spill = surface_point_line_spill(num_elements=1000,
                                     amount = 6.89, 
                                     start_position=(-46.52,-26.46,0),
                                     release_time=start_time,
                                     end_release_time=end_time,
                                     substance=substance,
                                     units='bbl',
                                     windage_range = (0.01,0.04))

My amount was 6.89 bbl (1.095 m^3), and I want to check if this amount would be release per day or if it's the total amount (in my scenario, 6.89 bbl needs to be a daily production value).

Thank you, and I'm sorry if those questions are answered somewhere. I couldn't find more info about it.
 @jay-hennen

**Comment by ChrisBarker-NOAA** [comment]
> Is it possible for me to change from kg to bbl or m^3, so my output is in the unit I need, or do I need to do it after?

You need to convert after -- this would be a nice feature, but it's a bit of work, as GNOME uses mass internally -- mass is conserved, volume is not.

> In:
```
spill = surface_point_line_spill(num_elements=1000,
amount = 6.89,
start_position=(-46.52,-26.46,0),
release_time=start_time,
end_release_time=end_time,
substance=substance,
units='bbl',
windage_range = (0.01,0.04))
```
> My amount was 6.89 bbl (1.095 m^3), and I want to check if this amount would be release per day or if it's the total amount (in my scenario, 6.89 bbl needs to be a daily production value).

That's the total, you will need to multiply by your release duration to get the release rate correct.

**Comment by ChrisBarker-NOAA** [comment]
you can re-open is you have additional questions.
