### ISSUE TITLE
Trouble with the GridWindMover

### ISSUE THREAD

**Issue by Gronohibari** [NOAA-ORR-ERD/PyGnome#150]
Hello everybody, im trying to model a spill and output as a shapefile using a netcdf that has more than 1 variables is that the reason that i get the GridWindMover_c.TextRead error ? My netcdf contains a grid with wind speed and wind direction data .  Also how should i format the c_GridWindMover function so it works ?? 

Thanks a lot in advance .

**Comment by ChrisBarker-NOAA** [comment]
The `GridWindsMover_c` code is the "older" code from GNOME 1 - we now have newer code that should be more flexible:

You should be able to use the new WindMover directly:

```
from gnome import scripting as gs

wm = gs.WindMover.from_netCDF('name_of_file.nc')
```
Here is the full signature:

```
gs.WindMover.from_netCDF?
Signature:
gs.WindMover.from_netCDF(
    filename=None,
    time_offset=0,
    scale_value=1,
    uncertain_duration=10800,
    uncertain_time_delay=0,
    uncertain_speed_scale=2.0,
    uncertain_angle_scale=0.4,
    default_num_method='RK2',
```
If this doesn't work, if you can set us the header of the netcdf file, we should be able to help.

`ncdump -h name_of_file.nc`

**Comment by ChrisBarker-NOAA** [comment]
Here: https://gnome.orr.noaa.gov/doc/pygnome/file_formats/netcdf.html

Is the specification of the netcdf formats PyGNOME should work with.

**Comment by Gronohibari** [comment]
> The `GridWindsMover_c` code is the "older" code from GNOME 1 - we now have newer code that should be more flexible:
> 
> You should be able to use the new WindMover directly:
> 
> ```
> from gnome import scripting as gs
> 
> wm = gs.WindMover.from_netCDF('name_of_file.nc')
> ```
> 
> Here is the full signature:
> 
> ```
> gs.WindMover.from_netCDF?
> Signature:
> gs.WindMover.from_netCDF(
>     filename=None,
>     time_offset=0,
>     scale_value=1,
>     uncertain_duration=10800,
>     uncertain_time_delay=0,
>     uncertain_speed_scale=2.0,
>     uncertain_angle_scale=0.4,
>     default_num_method='RK2',
> ```
> 
> If this doesn't work, if you can set us the header of the netcdf file, we should be able to help.
> 
> `ncdump -h name_of_file.nc`

Thanks a lot for the answer ! Sadly when i try the new mover command i get an error saying cant figure out what type of grid my nc is here is my net cdf header : root group (NETCDF3_64BIT data model, file format UNDEFINED):
    ADAPT_DT_MAX: 15.0
    ADAPT_DT_MIN: 3.0
    ADAPT_DT_START: 13.0
    AER_ANGEXP_OPT: 1
    AER_ANGEXP_VAL: 1.29999995232
    AER_AOD550_OPT: 1
    AER_AOD550_VAL: 0.119999997318
    AER_ASY_OPT: 1
    AER_ASY_VAL: 1.40129846432e-45
    AER_OPT: 0
    AER_SSA_OPT: 1
    AER_SSA_VAL: 1.40129846432e-45
    AER_TYPE: 1
    BLDT: 0.0
    BL_PBL_PHYSICS: 5
    BOTTOM-TOP_GRID_DIMENSION: 61
    BUCKET_J: -1.0
    BUCKET_MM: -1.0
    CEN_LAT: 45.4156112671
    CEN_LON: 24.0356445313
    CONST_Cp_DRY_AIR: 1004.5
    CONST_GRAVITY: 9.81
    CONST_RATIO_Rd_Rw: 0.622
    CONST_R_DRY_AIR: 287.0
    CONST_R_WATER: 461.4
    CUDT: 5.0
    CU_PHYSICS: 0
    Conventions: CF-1.8
    DAMPCOEF: 0.15000000596
    DAMP_OPT: 0
    DFI_OPT: 0
    DIFF_6TH_FACTOR: 0.10000000149
    DIFF_6TH_OPT: 2
    DIFF_OPT: 1
    DT: 14.9458332062
    DX: 3000.0
    DY: 3000.0
    EXPERIMENT: Production Run
    FEEDBACK: 0
    GFDDA_END_H: 0
    GFDDA_INTERVAL_M: 0
    GMT: 0.0
    GRAV_SETTLING: 0
    GRIDTYPE: C
    GRID_FDDA: 0
    GRID_ID: 3
    GRID_SFDDA: 0
    HYPSOMETRIC_OPT: 2
    ICLOUD: 1
    ICLOUD_CU: 0
    INSTITUTION: The NEWA Consortium
    ISFFLX: 1
    ISFTCFLX: 0
    ISHALLOW: 0
    ISICE: 24
    ISLAKE: 28
    ISOILWATER: 14
    ISURBAN: 1
    ISWATER: 16
    I_PARENT_START: 39
    JULDAY: 178
    JULYR: 2018
    J_PARENT_START: 39
    KHDIF: 0.0
    KM_OPT: 4
    KVDIF: 0.0
    MAP_PROJ: 1
    MAP_PROJ_CHAR: Lambert Conformal
    MFSHCONV: 0
    MMINLU: USGS
    MOAD_CEN_LAT: 54.0
    MOIST_ADV_OPT: 1
    MP_PHYSICS: 4
    NUM_LAND_CAT: 28
    OBS_NUDGE_OPT: 0
    PARENT_GRID_RATIO: 3
    PARENT_ID: 2
    POLE_LAT: 90.0
    POLE_LON: 0.0
    PREC_ACC_DT: 30.0
    RADT: 12.0
    RA_LW_PHYSICS: 4
    RA_SW_PHYSICS: 4
    SCALAR_ADV_OPT: 1
    SCALAR_PBLMIX: 0
    SF_LAKE_PHYSICS: 0
    SF_OCEAN_PHYSICS: 0
    SF_SFCLAY_PHYSICS: 2
    SF_SURFACE_PHYSICS: 2
    SF_URBAN_PHYSICS: 0
    SGFDDA_END_H: 0
    SGFDDA_INTERVAL_M: 0
    SHCU_PHYSICS: 0
    SIMULATION_INITIALIZATION_TYPE: REAL-DATA CASE
    SIMULATION_START_DATE: 2018-06-27_00:00:00
    SKEBS_ON: 0
    SMOOTH_OPTION: 2
    SOUTH-NORTH_GRID_DIMENSION: 1382
    SPEC_BDY_FINAL_MU: 1
    SST_UPDATE: 1
    STAND_LON: 15.0
    START_DATE: 2018-06-27_00:00:00
    SURFACE_INPUT_SOURCE: 1
    SWINT_OPT: 1
    SWRAD_SCAT: 1.0
    TITLE: Timeseries of the New European Wind Atlas from WRF V3.8.1
    TKE_ADV_OPT: 1
    TRACER_PBLMIX: 1
    TRUELAT1: 30.0
    TRUELAT2: 60.0
    USE_Q_DIABATIC: 0
    USE_THETA_M: 0
    WEST-EAST_GRID_DIMENSION: 1598
    W_DAMPING: 1
    YSU_TOPDOWN_PBLMIX: 0
    title: New European Wind Atlas: Mesoscale Time-Series
    authors: Andrea N. Hahmann
    summary: To be added

    dataset_pid: https://doi.org/10.11583/DTU.xxx
    institution: DTU Wind Energy
    license: CC BY NC 4.0
    distribution_statement: These data follow DTU Wind Energy standards; they are public and free of charge.
User assumes all risk for use of data. User must display citation in any publication or product using data.
User must contact DTU Wind Energy prior to any commercial use of data.

    cdm_data_type: Grid
    data_mode: Delayed-mode
    date_create: 2023-07-24T13:47:25
    date_update: 2023-07-24T13:47:25
    subject: Sitting, Wind Mapping, Wind Atlases, Resource assessment, Design conditions
    variable: LANDMASK, WD10, WS10
    history: 2023-07-25T11:16:29        daTap v0.2.0a4  https://wps.neweuropeanwindatlas.eu/api/mesoscale-ts/v1/get-data-bbox?southBoundLatitude=34.207729&northBoundLatitude=40.519149&westBoundLongitude=18.852539&eastBoundLongitude=30.102539&variable=LANDMASK&variable=WD10&variable=WS10&dt_start=2013-08-15T00:00:00&dt_stop=2013-08-15T23:30:00
2023-07-25T11:16:29     daTap v0.2.0a4  LANDMASK, WD10, WS10 subsetted
2023-07-25T11:16:29     daTap v0.2.0a4  dataset aggregated
    southBoundLatitude: 34.207729
    northBoundLatitude: 40.519149
    westBoundLongitude: 18.852539
    eastBoundLongitude: 30.102539
    verticalExtentMinimum: 50.0
    verticalExtentMaximum: 500.0
    temporalExtentMinimum: 2013-08-15T00:00:00
    temporalExtentMaximum: 2013-08-15T23:30:00
    subset_pid: https://wps.neweuropeanwindatlas.eu/api/mesoscale-ts/v1/get-data-bbox?southBoundLatitude=34.207729&northBoundLatitude=40.519149&westBoundLongitude=18.852539&eastBoundLongitude=30.102539&variable=LANDMASK&variable=WD10&variable=WS10&dt_start=2013-08-15T00:00:00&dt_stop=2013-08-15T23:30:00
    dimensions(sizes): south_north(245), west_east(347), time(48)
    variables(dimensions): float64 ←[4mwest_east←[0m(west_east), int8 ←[4mLANDMASK←[0m(south_north,west_east), float32 ←[4mXLAT←[0m(south_north,west_east), float32 ←[4mXLON←[0m(south_north,west_east), float64 ←[4msouth_north←[0m(south_north), float32 ←[4mWD10←[0m(time,south_north,west_east), float32 ←[4mWS10←[0m(time,south_north,west_east), int32 ←[4mtime←[0m(time), int8 ←[4mcrs←[0m()
    groups:

**Comment by Gronohibari** [comment]
> Here: https://gnome.orr.noaa.gov/doc/pygnome/file_formats/netcdf.html
> 
> Is the specification of the netcdf formats PyGNOME should work with.

Thanks a lot reading the specifications helped me find a more suitable netcdf file :D !

**Comment by ChrisBarker-NOAA** [comment]
Great -- glad it worked out. We added that section of the docs fairly recently -- good thing we did!
