### ISSUE TITLE
Reading in multiple netCDF files?

### ISSUE THREAD

**Issue by sbocajlien** [NOAA-ORR-ERD/PyGnome#151]
Hi,  

In the documentation, it says the method of having a master file is deprecated, and you can just pass pygnome a list of files.  Can you provide the proper syntax or code snippet for how that works?  All of the examples and test scripts I've seen only use a single .nc file.

Thanks!

Example 1 – Filename: MyMasterFileEx.txt

NetCDF Files
[FILE]  :day1.nc
[FILE]  :day2.nc
[FILE]  :day3.nc
[FILE]  :day4.nc
[FILE]  :day5.nc
[FILE]  :day6.nc

**Comment by coconnor8** [comment]
We are still working on documentation for this but there is an example
using multiple files in testing_scripts/script_ice/script_ice.py.

Instead of the old master file you now can pass in a python list. For
example -

    file_list = ['day1.nc',
          'day2.nc',
          'day3.nc',
          'day4.nc',
          'day5.nc',
          'day6.nc',
          ]
    current = gs.GridCurrent.from_netCDF(file_list)
    py_current_mover = gs.CurrentMover(current=current)
    model.movers += py_current_mover

The files must be in order and in netcdf3 format.

**Comment by ChrisBarker-NOAA** [comment]
NOTE:
> in netcdf3 format.

Or "NETCDF4 CLASSIC". If you're not sure what you have, give it a try :-).

If there is an issue with the format, you can convert with tools like NCO:

https://nco.sourceforge.net/

-CHB

**Comment by sbocajlien** [comment]
Thanks Chris!

I got it working.  Works great!  

Random other question:  I originally used conda to try to build this on my M1 mac.  It wasn’t able to locate the following packages for osx-arm64:

 py_gd[version='>=2.0']
 cell_tree2d

Do these exist somewhere?  If not, are there plans to support osx-arm64?

Fortunately, I have a couple intel macs, which is where I’m running it now, and it seems happy.

THanks!!
-Neil

**Comment by ChrisBarker-NOAA** [comment]
yeah, M1 is still newish, and we haven't rebuilt that in a while.

I'll take a look -- if there's a libgd build for osx-arm64, then it should be straightforward.

And I may be getting an M1 machine myself soon, so would actually be able to debug it if there are any issues.
