### ISSUE TITLE
LinAlg error 

### ISSUE THREAD

**Issue by Gronohibari** [NOAA-ORR-ERD/PyGnome#153]
Hello everybody,
Im trying to model an oil spill with a pretty simple scripts using 2 netcdf files . 
But i get these errors and the surface concentration field on my attribute table seems to have too low values some even being 0 .
This is the erros i get when i run the code : 
c:\users\user\desktop\pygnome\pygnome-main\py_gnome\gnome\environment\gridded_objects_base.py:622: UserWarning: Variable0 units is not supported: m s**-1Using them unconverted as m/s
  warnings.warn("{0} units is not supported: {1}"
c:\users\user\desktop\pygnome\pygnome-main\py_gnome\gnome\utilities\surface_concentration.py:88: UserWarning: LinAlg error occurred in surface concentration calculations.
  warnings.warn("LinAlg error occurred in surface concentration calculations.")

This is the code i use if it helps : 
print("Importing gnome")
from gnome import scripting
from gnome import utilities
from gnome.outputters import NetCDFOutput, ShapeOutput, Renderer
import datetime

# Setting the data
bna_map = r'C:\Users\User\Desktop\gnometest\karpathosmap.bna'
wind_data = r'C:\Users\User\Desktop\gnometest\karpathoswind.nc'
cur_data = r"C:\Users\User\Desktop\gnometest\karpathoscur.nc"
mymap = scripting.MapFromBNA(filename=bna_map, refloat_halflife=-1)
# Spill coordinates
spill_coords = (26.833333,35.866667)
start_time = '2013-11-2T01:00:00'
duration = datetime.timedelta(days=21)
time_step = datetime.timedelta(hours=1)

# Model
model = scripting.Model(start_time=start_time,
                        duration=duration,
                        time_step=time_step
                        )
print("Map data are adding up ")
# Create the map using MapFromBNA class
model.map = scripting.MapFromBNA(filename=bna_map, refloat_halflife=-1)
print("Loading wind data ")
# Create the mover
wind_mover = scripting.WindMover.from_netCDF(wind_data)
print("Load current data")
current_mover = scripting.CurrentMover.from_netCDF(cur_data)

print("Adding the movers")
model.movers += wind_mover
model.movers += current_mover

print("Setting up oil parameters")
oil_density_kg_per_liter = 0.85  
spill_amount_kg = 850
print("Setting up the model")
# Set the modelpo
model.spills += scripting.surface_point_line_spill(num_elements=1000,
                                                  start_position=spill_coords,
                                                  release_time=model.start_time,
                                                  amount=spill_amount_kg,
                                                  units='kg')

# Output it as a shapefile
output_file = r"C:\Users\User\Desktop\gnometest\karpathosspill2.shp"
model.outputters += ShapeOutput(output_file, zip_output=True, surface_conc='kde')
map_BB = mymap.get_map_bounding_box()

print("Simulation start")
#MODEL RUN
model.full_run()
print("End of program")

**Comment by coconnor8** [comment]
It looks like those messages are warnings rather than errors. The first one is about not recognizing units in the file but it is defaulting to the correct unit. We have recently added some units so this warning may go away.
The other one might be a sign of something wrong, either with the model setup, or possibly a bug. It would be helpful if you could send a Save file, or at least the files that get loaded in by your script so we could take a look at it.

**Comment by AmyMacFadyen** [comment]
The LinAlg errors from the surface concentration calculation typically arise when all the particles are on top of each other (not moving). I'd suggest turning this off until you can visualize the model results and ensure the particles are moving as expected.

**Comment by Gronohibari** [comment]
@coconnor8 
I could send them to someone how could i send the netcdf files and the bna map i used to run this script ? 
Also the particles arent on top of each other , the oil spill gets modelled fine but the surface concetration numbers are 0 or really really low .

**Comment by coconnor8** [comment]
You should be able to attach them to your comment, but if the files are too big you can take a subset and/or send them to this email - webgnome.help@noaa.gov

**Comment by ChrisBarker-NOAA** [comment]
I don't see a RandomMover in your script -- that is used to simulate diffusion, and without it, the elements tend to stay all piled up on top of each other, which might cause the error.

The WindMover also spreads them our a bit -- so it may not look like there are all on top of each-other, but there could be some overlapping.

Closing this fro now -- but fee free to re-open (or make a new issue) if you haven't figure it out.
