### ISSUE TITLE
Testing problems

### ISSUE THREAD

**Issue by 7eatriz** [NOAA-ORR-ERD/PyGnome#154]
I'm encountering an issue when trying to run the PyGnome model with Adios. The code runs fine in another notebook, but I'm getting the following error
![image](https://github.com/NOAA-ORR-ERD/PyGnome/assets/170749601/cffc7fcf-96ac-4eef-8e4d-f3cdc0b89b78)
The PyGnome model was installed with Adios, and the code runs well in another notebook, but I'm encountering an error and don't know how to correct it. Could you please help me?

**Comment by 7eatriz** [comment]
I tried reinstalling with the latest code (1.1.11 version PyGnome from https://github.com/NOAA-ORR-ERD/PyGNOME/releases) and it worked, my script ran very well, thanks to Caitlin O'Connor (NOAA Federal) for all the help and explanation.

**Comment by ChrisBarker-NOAA** [comment]
Glad it worked out -- thanks for the success report.
