### ISSUE TITLE
Possible naming error liblib_gnome.so? Triggers cannot find libgnome.so when building

### ISSUE THREAD

**Issue by moisespr123** [NOAA-ORR-ERD/PyGnome#155]
Below is the output. It seems for some reason the naming is liblib_gnome.so, and it fails to find lib_gnome.so.

Now, I'm using an "unsupported environment" in that I'm attempting to run this purely using python and pip3 without conda. Not sure if related, but this happens when cloning from the main branch.

```
-- Install configuration: "Release"
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/liblib_gnome.so
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_basic_types.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_basic_types.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_mover.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_mover.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_helpers.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_helpers.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_wind_mover.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_wind_mover.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_current_mover.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_current_mover.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_cats_mover.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_cats_mover.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_component_mover.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_component_mover.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_gridcurrent_mover.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_gridcurrent_mover.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_gridwind_mover.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_gridwind_mover.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_ice_mover.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_ice_mover.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_ice_wind_mover.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_ice_wind_mover.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_currentcycle_mover.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_currentcycle_mover.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_ossm_time.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_ossm_time.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_random_mover.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_random_mover.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_random_mover_3d.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_random_mover_3d.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_rise_velocity_mover.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_rise_velocity_mover.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_land_check.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_land_check.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_grid_map.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_grid_map.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_shio_time.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_shio_time.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_grid.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_grid.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_grid_rect.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_grid_rect.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_grid_curv.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_grid_curv.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_weatherers.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/cy_gnome/cy_weatherers.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/utilities/geometry/libpoint_in_polygon.so
35.81       -- Installing: /tmp/tmpmfkn88k6/wheel/platlib/gnome/utilities/geometry/cy_point_in_polygon.cpython-39-x86_64-linux-gnu.so
35.81       -- Set runtime path of "/tmp/tmpmfkn88k6/wheel/platlib/gnome/utilities/geometry/cy_point_in_polygon.cpython-39-x86_64-linux-gnu.so" to "$ORIGIN/."
35.81       *** Making wheel...
35.81       Traceback (most recent call last):
35.81         File "/drift-venv/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
35.81           main()
35.81         File "/drift-venv/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
35.81           json_out['return_val'] = hook(**hook_input['kwargs'])
35.81         File "/drift-venv/lib64/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
35.81           return _build_backend().build_wheel(wheel_directory, config_settings,
35.81         File "/tmp/pip-build-env-_n9e4gsg/overlay/lib/python3.9/site-packages/scikit_build_core/build/__init__.py", line 31, in build_wheel
35.81           return _build_wheel_impl(
35.81         File "/tmp/pip-build-env-_n9e4gsg/overlay/lib/python3.9/site-packages/scikit_build_core/build/wheel.py", line 361, in _build_wheel_impl
35.81           shutil.copyfile(filepath, package_dir)
35.81         File "/usr/lib64/python3.9/shutil.py", line 264, in copyfile
35.81           with open(src, 'rb') as fsrc:
35.81       FileNotFoundError: [Errno 2] No such file or directory: 'gnome/cy_gnome/libgnome.so'
35.81       [end of output]
```

This fails the installation. I'm using `python -m pip install ./` as the documentation tells.

**Comment by ChrisBarker-NOAA** [comment]
Hmm -- this is familiar, I thought we'd fixed it.

@JamesMakela-NOAA:  do remember this? what's up?

meanwhile: is this the main branch?

If so, try building the develop branch -- perhaps we haven't gotten the fix in to main yet.

**Comment by JamesMakela-NOAA** [comment]
On Wed, Jul 17, 2024 at 11:38 AM Moises Cardona ***@***.***>
wrote:

> Below is the output. It seems for some reason the naming is
> liblib_gnome.so, and it fails to find lib_gnome.so.
>
> Now, I'm using an "unsupported environment" in that I'm attempting to run
> this purely using python and pip3 without conda. Not sure if related, but
> this happens when cloning from the main branch.
>
Well, this is not something I would recommend.  Is there a good reason for
not using conda?  Also, what exactly is the environment you are using?  It
looks like a unix-like system.

We have been using Anaconda for awhile now, and the environment that
PyGnome operates in will work best using it.

-- Install configuration: "Release"

**Comment by ChrisBarker-NOAA** [comment]
> We have been using Anaconda for awhile now, and the environment that
PyGnome operates in will work best using it.

True, but that's mostly about the dependencies -- if you have scikit build working, then PyGNOME itself should build fine.

conda may be putting libs in different places, but it's not giving them different names ...

**Comment by moisespr123** [comment]
> Well, this is not something I would recommend. Is there a good reason for not using conda? Also, what exactly is the environment you are using? It looks like a unix-like system. We have been using Anaconda for awhile now, and the environment that PyGnome operates in will work best using it.

We are not allowed to use conda and need to use specific packages. The environment is Python 3.9 under a docker rpm-based distribution. I've working in the past with @ChrisBarker-NOAA (see previous issues from my username) trying to solve issues and everything went well until this recent rebuild. This was with the master branch of this repository. I'm now trying to get build v1.0.0 which I think at once worked.

PS the OilLibrary project builds just fine. I'm also targeting the latest version on the dependencies. Interestingly, I also get a warning about using deprecated NumPy API but I think this is normal as part of the C++ build.

I'll keep this updated if I find something else.

**Comment by moisespr123** [comment]
PS I found the issue.

I had a hardcoded docker line:

```
RUN ln -s /PyGnome/py_gnome/gnome/cy_gnome/libgnome.cpython-36m-x86_64-linux-gnu.so /PyGnome/py_gnome/gnome/cy_gnome/libgnome.so
```

Somehow this was needed before. It's no longer the case. I removed it and it now build properly without conda.

**Comment by ChrisBarker-NOAA** [comment]
Great, thanks for the report.

PyGNOME is now using a scikit-build system, replacing the very hacky system we had in the past, hence the change. And we're running it on CentOS so it was tested on a similar system. (Or we're -- moving to Ubuntu now) 

NOTE: it does not work with numpy 2 - I just pinned it to <2 in the conda requirements, but if you're not using conda, that won't help ;-) -. But be aware.

It should be numpy 2 and python 3.12 compatible soon.

- CHB

**Comment by moisespr123** [comment]
Excellent. Thanks for the input. I will pin numpy <2 for now and perform a rebuild.

**Comment by ChrisBarker-NOAA** [comment]
BTW -- it's hard for us to maintain it, but if you provide a pip_requirements fijle that works (at least for Linux), we can put it in the repo.

It will probably look a lot like the conda_requirements file, but not exactly the same :-(

Also -- we've been a bit lazy about putting some of our smaller pacakges on PyPi -- give us a nudge (or better yet, PRs) and we can get that done.

-CHB

**Comment by moisespr123** [comment]
No problem. My requirements file is a bit messy but seem to work.

For the smaller packages (do you mean the other NOAA dependencies?) I'm cloning and building manually with pip as well. It is a somewhat messy requirements file that may seem to make the other packages build without issues.

**Comment by ChrisBarker-NOAA** [comment]
yes, the other NOAA dependencies.

I've put the latest pynucos on PyPi.

py_gd is a problem -- someone is using that name (for something trivial and unsupported, as far as I can tell :-( ) -- so I"ll need to find a new name: "py_libgd" maybe? It's also a pain to build, but at least the sdist could be there, and it could be buildable on Linux.

In short -- it would be nice to have all this usable without conda, and we'll accept help to do that.

**Comment by ChrisBarker-NOAA** [comment]
one more note: mapbox-earcut has broken (with numpy2.0) wheels on PyPi -- not an issue until we get to numpy 2, and I've fixed the build on conda-forge -- but it's out of our hands. not sure how hard it is to build that from source outside of conda.
