### ISSUE TITLE
Trouble with trying to add ERA 5 data on the Wind Enviroment Object

### ISSUE THREAD

**Issue by Gronohibari12** [NOAA-ORR-ERD/PyGnome#158]
Hello everyone ! 
I am trying to create a wind environment object from ERA - 5 data and i seem to get this error : 
import gnome.scripting as gs
fn =r"C:\Users\User\Desktop\aegeoerasmus\testdata\windata.nc"
wind = gs.GridWind.from_netCDF(filename=fn)
Traceback (most recent call last):

  Cell In[4], line 1
    wind = gs.GridWind.from_netCDF(filename=fn)

  File c:\users\user\desktop\pygnome\pygnome-main\py_gnome\gnome\environment\gridded_objects_base.py:906 in from_netCDF
    var.init_from_netCDF(*args, **kwargs)

  File c:\users\user\desktop\pygnome\pygnome-main\py_gnome\gnome\environment\gridded_objects_base.py:844 in init_from_netCDF
    depth = Depth.from_netCDF(grid_file=grid_file,

  File c:\users\user\desktop\pygnome\pygnome-main\py_gnome\gnome\environment\gridded_objects_base.py:400 in from_netCDF
    return gridded.depth.Depth.from_netCDF(*args, **kwargs)

  File ~\.conda\envs\gnome\lib\site-packages\gridded\depth.py:677 in from_netCDF
    cls = Depth._get_depth_type(df, depth_type, topology, _default_types)

  File ~\.conda\envs\gnome\lib\site-packages\gridded\depth.py:725 in _get_depth_type
    L_Depth.from_netCDF(dataset=dataset)

  File ~\.conda\envs\gnome\lib\site-packages\gridded\depth.py:140 in from_netCDF
    vname = cls._gen_varname(filename, dataset, [tn], [tln])

  File ~\.conda\envs\gnome\lib\site-packages\gridded\depth.py:92 in _gen_varname
    raise KeyError("Default names not found.")

KeyError: 'Default names not found.'

I have changed the variable names a lot of time and i have also tried this version : wind = gs.GridWind.from_netCDF(
    filename=fn,
    names_list=['air_u', 'air_v']
) and i get the same error. 

Any idea how to fix this ? 
Thanks a lot for ur continuous work and help !

**Comment by ChrisBarker-NOAA** [comment]
from the error, it looks like our code is being confused by the "depth" variables -- that is, the vertical grid.

In practice, we only really use 3D model results for ocean currents, as the surface winds are what's needed by GNOME.

with a quick google, I see:

> ERA5 is available on:
> ...
> Single levels

Can you get the data as a file with only the surface winds? that will hopefully work out of the box.

Otherwise, if you can point us to an (ideally small) sample file, we can take a look -- it would be good for this to work as is.

**Comment by Gronohibari12** [comment]
You are right after removing a dimension called pressure level(even if it was only 1) it was able to load thanks a lot !
