### ISSUE TITLE
Some questions about polygon release.

### ISSUE THREAD

**Issue by Gronohibari12** [NOAA-ORR-ERD/PyGnome#159]
Hello everyone ! 
1)Im trying to simulate a polygon release. Ideally, i would like to use the Continuous Polygon Release object but it says it doesnt work is this still the case? 
2)Right now im trying to simulate a simple polygon release the model runs but the output is empty no particles end up being released. 
Is there something wrong with how i set up the oil spill? 
3) Also is there a way other than the continuous polygon release to release elements every 24 hours from the polygons (area based) on a model that has a 1 hour time step ? 

This is the code that i currently use for a test model(I know a lot of imports) : 

```
print("Importing gnome")
import gnome
import gnome.scripting as gs
from gnome import utilities
from gnome.outputters import NetCDFOutput, ShapeOutput, Renderer
from gnome.movers.random_movers import RandomMover
from gnome.environment import GridWind, GridCurrent  # Import directly from gnome.environment
from gnome.spills.release import PolygonRelease
from gnome.spills.spill import Spill

print("Importing other libraries")
import geopandas as gpd
import datetime

# Setting the data
bna_map = r"C:\Users\User\Desktop\aegeoerasmus\aegeomap.bna"
wind_data = r'C:\Users\User\Desktop\aegeoerasmus\testdata\modwind.nc'
cur_data = r'C:\Users\User\Desktop\aegeoerasmus\testdata\curdata.nc'
mymap = gs.MapFromBNA(filename=bna_map, refloat_halflife=-1)
print("Create the model")
# Create the model
model = gs.Model(map=mymap)
print("Adding enviroment data")
# Environments
wind = GridWind.from_netCDF(filename=wind_data)
current = gnome.environment.environment_objects.GridCurrent.from_netCDF(filename=cur_data)
print("Setting up the enviroments")
# Add environments to the model
model.environment += wind
model.environment += current
print("Model time variables")
#Model timers
start_time = datetime.datetime(2016, 4, 2, 1, 0, 0)  # Ensure this is a datetime object
end_release = datetime.datetime(2016, 4, 7, 1, 0, 0)
duration = datetime.timedelta(days=5)
time_step = datetime.timedelta(hours=1)
print("Creating the polygons for the spill")
#Polygon spill
# Define the file path for the shapefile
shapefile_path = r"C:\Users\User\Desktop\aegeoerasmus\testdata\test.shp"

# Load the shapefile using geopandas
gdf = gpd.read_file(shapefile_path)

# Extract the geometries as a list of Shapely polygons
polygons = gdf.geometry.tolist()

polygon_release = PolygonRelease(
    release_time=start_time,
    end_release_time=end_release,
    polygons=polygons,
    num_per_timestep=1000  # Number of particles per timestep
)

# Wrap the PolygonRelease in a Spill object
polygon_spill = Spill(release=polygon_release)

# Add the Spill to the model's spills
model.spills += polygon_spill

print("Model data parameters")
# Model
model = gs.Model(start_time=start_time,
                        duration=duration,
                        time_step=time_step
                        )
print("Map data are adding up ")
# Create the map using MapFromBNA class
model.map = gs.MapFromBNA(filename=bna_map, refloat_halflife=-1)
print("Loading wind data ")
# Create the mover
wind_mover = gs.WindMover.from_netCDF(wind_data)
print("Load current data")
current_mover = gs.CurrentMover.from_netCDF(cur_data)
random_mover = RandomMover(diffusion_coef=100000.0, uncertain_factor=2.0)

print("Adding the movers")
model.movers += wind_mover
model.movers += current_mover
model.movers += random_mover
print("Setting up oil parameters")
oil_density_kg_per_liter = 0.800  # Density of oil in kilograms per liter (adjust as needed)
spill_amount_kg = 512
print("Setting up the model")
# Set the modelpo

                                                

# Output it as a shapefile
#output_file = r"C:\Users\User\Desktop\gnometest\pelopnew.shp"
#model.outputters += ShapeOutput(output_file, zip_output=True, surface_conc='kde')
map_BB = mymap.get_map_bounding_box()
renderer = Renderer(map_filename=bna_map,
                    output_dir=r"C:\Users\User\Desktop\gnometest",
                    output_timestep=time_step,
                    map_BB=map_BB)
model.outputters += renderer
print("Simulation start")
# Run the model
model.full_run()
print("End of program")
```

**Comment by ChrisBarker-NOAA** [comment]
1) I'm trying to simulate a polygon release. Ideally, i would like to use the Continuous Polygon Release object but it says it doesnt work is this still the case?

yes -- there is no continuous release from a polygon -- maybe some day :-)  -- but the fact that you have a need might help push it higher on the list.

2) Right now im trying to simulate a simple polygon release the model runs but the output is empty no particles end up being released. Is there something wrong with how i set up the oil spill?

I'll comment in the code, if I see something.

3) Also is there a way other than the continuous polygon release to release elements every 24 hours from the polygons (area based) on a model that has a 1 hour time step ?

You could set up multiple polygon releases, one each an hour apart, if I understand the question correctly.

Notes on your code:

(if you put triple back-ticks around code in here, it will look like code. when. rendered -- I added that to your original post)

```
print("Importing gnome")
import gnome
import gnome.scripting as gs
from gnome import utilities
from gnome.outputters import NetCDFOutput, ShapeOutput, Renderer
from gnome.movers.random_movers import RandomMover
from gnome.environment import GridWind, GridCurrent  # Import directly from gnome.environment
from gnome.spills.release import PolygonRelease
from gnome.spills.spill import Spill
```
most of these imports are uneeded -- the gnome, scripting module is a placeholder for all the names you are liley to need for scripting, so, e.g.:

```
import gnome.scripting as gs

# and then
gs.GridCurrent
# is available
```

print("Importing other libraries")
import geopandas as gpd
import datetime

# Setting the data
bna_map = r"C:\Users\User\Desktop\aegeoerasmus\aegeomap.bna"
wind_data = r'C:\Users\User\Desktop\aegeoerasmus\testdata\modwind.nc'
cur_data = r'C:\Users\User\Desktop\aegeoerasmus\testdata\curdata.nc'
mymap = gs.MapFromBNA(filename=bna_map, refloat_halflife=-1)
print("Create the model")
```
this all looks good
```
# Create the model
model = gs.Model(map=mymap)
print("Adding enviroment data")
# Environments
wind = GridWind.from_netCDF(filename=wind_data)
current = gnome.environment.environment_objects.GridCurrent.from_netCDF(filename=cur_data)
print("Setting up the enviroments")
```

as above:  `current = gs.GridCurrent.from_netCDF(filename=cur_data)` - but it's the same thing.

```
# Add environments to the model
model.environment += wind
model.environment += current
```

You pretty never need to add the environment objects to the model -- rather, you use the environment objects to build "Movers", and those are added to the model. The distinction is because some environment object, e.g. winds are used in more than one place: e.g. Wind is used in a WindMover and also in weathering.

And while in the real world, there is only one current, and one wind, etc -- in the model you can have multiple version of these, that can be mixed and matched in various ways.

So:
```
current = gs.GridCurrent.from_netCDF(filename=cur_data)
cur_mover = gs.CurrentMover(current)
model.movers += cur_mover
```

etc...

```
print("Model time variables")
#Model timers
start_time = datetime.datetime(2016, 4, 2, 1, 0, 0)  # Ensure this is a datetime object
end_release = datetime.datetime(2016, 4, 7, 1, 0, 0)
duration = datetime.timedelta(days=5)
time_step = datetime.timedelta(hours=1)
```
This is correct, but most of PYGNOME will take ISO strings, if that's easier:
`start_time = "2016-04-01T00:00"` 

and there are utilities for timedelta:
`gs.days(5)`

```
print("Creating the polygons for the spill")
#Polygon spill
# Define the file path for the shapefile
shapefile_path = r"C:\Users\User\Desktop\aegeoerasmus\testdata\test.shp"

# Load the shapefile using geopandas
gdf = gpd.read_file(shapefile_path)

# Extract the geometries as a list of Shapely polygons
polygons = gdf.geometry.tolist()

polygon_release = PolygonRelease(
    release_time=start_time,
    end_release_time=end_release,
    polygons=polygons,
    num_per_timestep=1000  # Number of particles per timestep
)

# Wrap the PolygonRelease in a Spill object
polygon_spill = Spill(release=polygon_release)

# Add the Spill to the model's spills
model.spills += polygon_spill

```
This looks correct, though you can probably use the:

`gs.polygon_release_spill` utility to make it easier.

```
print("Model data parameters")
# Model
model = gs.Model(start_time=start_time,
                        duration=duration,
                        time_step=time_step
                        )
print("Map data are adding up ")
# Create the map using MapFromBNA class
model.map = gs.MapFromBNA(filename=bna_map, refloat_halflife=-1)
print("Loading wind data ")
# Create the mover
wind_mover = gs.WindMover.from_netCDF(wind_data)
print("Load current data")
current_mover = gs.CurrentMover.from_netCDF(cur_data)
```
Ahh -- her you are using. the Mover from_netcdf utilities -- which is great but then there is no need to create the environment objects above.
```

random_mover = RandomMover(diffusion_coef=100000.0, uncertain_factor=2.0)

print("Adding the movers")
model.movers += wind_mover
model.movers += current_mover
model.movers += random_mover
print("Setting up oil parameters")
oil_density_kg_per_liter = 0.800  # Density of oil in kilograms per liter (adjust as needed)
spill_amount_kg = 512
                                         
# Output it as a shapefile
#output_file = r"C:\Users\User\Desktop\gnometest\pelopnew.shp"
#model.outputters += ShapeOutput(output_file, zip_output=True, surface_conc='kde')
map_BB = mymap.get_map_bounding_box()
renderer = Renderer(map_filename=bna_map,
                    output_dir=r"C:\Users\User\Desktop\gnometest",
                    output_timestep=time_step,
                    map_BB=map_BB)
```
I think what you want to set is the "viewport" -- but the Renderer should. default to the map's bounds anyway.
```
model.outputters += renderer
print("Simulation start")
# Run the model
model.full_run()
print("End of program")
```

I can't see anything wrong here, without seeing what's in your data files.

But one thing to be careful of -- longitude can be specified in -180--180 degrees or 0--360 degrees. PYGNME can work with either, but everything needs to be specified in t he same longitude coordinate system -- winds, currents, map, spills ...

Hope this helps.

If you're still having trouble, if you can point us to some (ideally small) sample data files, we might be able to see what's wrong.

**Comment by coconnor8** [comment]
I'm not sure if you copied your code correctly but what you posted has the model created twice. The second time is right after the spill is created and added to the original model. You add the map and movers again, but not the spill. So I think the first model with the spill is replaced by the second one without it before the model is run.

**Comment by ChrisBarker-NOAA** [comment]
Good catch, thanks!

**Comment by Gronohibari12** [comment]
Thank you guys so much for your replies!!
You were right i was creating 2 models so now it worked !
As i am planning to do a long term simulation do you think that creating a loop where oil spill polygon objects are created for every 24 hours and added would work ? 
Again thank you.

**Comment by ChrisBarker-NOAA** [comment]
well, for a few hours, absolutely -- but at some point it would get very, very big.

how long are you thinking of? what's the use-case for starting more in a polygon every 14 hours?

**Comment by Gronohibari12** [comment]
Im trying to simulate a continuous oil spill release from a high traffic area for like a month to see where most of it gets beached. 
So i was thinking about releasing elements every 24 hours from the same polygon area.

**Comment by ChrisBarker-NOAA** [comment]
hmm -- as long as the number of elements isn't too large (100?), that should work.

Another option would be to do a bunch of point continuous releases, scattered over the region.

**Comment by Gronohibari12** [comment]
Thanks so much for all the advice !
