### ISSUE TITLE
Where is the testdata for running the scripts?

### ISSUE THREAD

**Issue by rsignell-usgs** [NOAA-ORR-ERD/PyGnome#16]
The test scripts want to load local data, like this:

https://github.com/NOAA-ORR-ERD/PyGnome/blob/master/py_gnome/scripts/script_boston/script_boston.py#L84-L85

```
    curr_file = get_datafile(os.path.join(base_dir, r"./EbbTides.cur"))
    tide_file = get_datafile(os.path.join(base_dir, r"./EbbTidesShio.txt"))
    curr_file = get_datafile(os.path.join(base_dir,
                             r"./MerrimackMassCoast.cur"))
    tide_file = get_datafile(os.path.join(base_dir,
                             r"./MerrimackMassCoastOSSM.txt"))
    curr_file = get_datafile(os.path.join(base_dir, r"MassBaySewage.cur"))
    component_file1 = get_datafile(os.path.join(base_dir, r"./WAC10msNW.cur"))
    component_file2 = get_datafile(os.path.join(base_dir, r"./WAC10msSW.cur"))
```

Where do I find this data?

I tried google searching and it landed me on this web site:
http://gnome.orr.noaa.gov/py_gnome_testdata/
which times out.

It might be nice to zip these files and add them to the release (a slick feature of github)

**Comment by ChrisBarker-NOAA** [comment]
That get_datafile() call is supposed to auto-magically download it for you.

I tried google searching and it landed me on this web site:
http://gnome.orr.noaa.gov/py_gnome_testdata/

Yup - that's the place. We're in the middle of re-configuring servers right
now, but I thought that was working...

It might be nice to zip these files and add them to the release (a slick
feature of github

I'll look into that. We didn't put them in the repo, 'cause some of them
are pretty big. Not sure how big files we can put in a release.

And a lot are used for test code, so we want to be able to run straight
from the repo.

-CHB

**Comment by rsignell-usgs** [comment]
It seems down for everyone:
http://downforeveryoneorjustme.com/http://gnome.orr.noaa.gov/py_gnome_testdata/

**Comment by rsignell-usgs** [comment]
Is there another way I could get the data?  I was hoping to run this today prior to the LCS meeting tomorrow....

**Comment by ChrisBarker-NOAA** [comment]
Fixed now! turns out our internal nameserver was still pointing to the old
server, so we didn't notice the new one was blocked.

http://downforeveryoneorjustme.com/http://gnome.orr.noaa.gov/py_gnome_testdata/

see if those files auto-download for you now.

-CHB



On Wed, Jan 13, 2016 at 8:19 AM, Rich Signell <notifications@github.com>
wrote:

> Is there another way I could get the data? I was hoping to run this today
> prior to the LCS meeting tomorrow....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NOAA-ORR-ERD/PyGnome/issues/16#issuecomment-171347601>
> .
>



-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by rsignell-usgs** [comment]
Yes, it's working now!   I ran `script_boston.py` and got a netcdf file back!

**Comment by ChrisBarker-NOAA** [comment]
whoo hoo!

We're going to push a new version to gitHub today -- but I don't think
anything's changed in what you're looking at -- except that you can get an
animated GIF now.

Thanks for trying it out -- you found a server config error we couldn't see
from inside our network.

-CHB



On Wed, Jan 13, 2016 at 8:51 AM, Rich Signell <notifications@github.com>
wrote:

> Yes, it's working now! I ran script_boston.py and got a netcdf file back!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NOAA-ORR-ERD/PyGnome/issues/16#issuecomment-171361560>
> .
>



-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by rsignell-usgs** [comment]
See this for Large File Support on github.   Very cool:
http://www.infoq.com/news/2015/04/github-large-file-storage

**Comment by ChrisBarker-NOAA** [comment]
cool -- could be useful, once gitHub supports it.

Though this system has worked pretty well, at least if you don't try it in
the middle of a server transition :-)

-CHB


On Thu, Jan 14, 2016 at 1:31 PM, Rich Signell <notifications@github.com>
wrote:

> See this for Large File Support on github. Very cool:
> http://www.infoq.com/news/2015/04/github-large-file-storage
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NOAA-ORR-ERD/PyGnome/issues/16#issuecomment-171786063>
> .
>



-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov
