### ISSUE TITLE
Inquiry Regarding Handling Multiple Tidal Constituent Files in PyGNOME

### ISSUE THREAD

**Issue by Misiorama** [NOAA-ORR-ERD/PyGnome#168]
Hello, 
I understand that GNOME typically expects a single .shio file containing tidal constituent data for a specific location.
However, given the spatial variability of tidal dynamics in my study area, using a single .shio file does not seem adequate for accurately representing the local tidal currents.

I want to incorporate the spatial variation of tidal constituents (from FES2022 .nc files) into my PyGNOME model. Ideally, I would like to either: Use multiple .shio files, each representing a specific region or point within the domain. Alternatively, implement the gridded tidal data directly into the model if supported. This is possible?

Thanks in advance

**Comment by ChrisBarker-NOAA** [comment]
I've provided some into in my comment to #170, but I'll provide a bit more context here.

> I want to incorporate the spatial variation of tidal constituents (from FES2022 .nc files) into my PyGNOME model. Ideally, I would like to either: Use multiple .shio files, each representing a specific region or point within the domain. Alternatively, implement the gridded tidal data directly into the model if supported. 

This is what you are working with, yes? 
`https://www.aviso.altimetry.fr/en/data/products/auxiliary-products/global-tide-fes/release-fes22.html`

As it happens, we have only become aware of that product, and have not yet developed a way to use it directly.

We may or may not build support for it directly into GNOME, but for the moment, the option is to use the FES2022 model to generate a time series of gridded velocities for the time of interest, and then us that in PyGNOME.

The velocities can be in any fomrat supported by GNOME: likely a UGRID compliant netcdf file:
 - https://gnome.orr.noaa.gov/doc/pygnome/file_formats/netcdf.html

I haven't looked closely, but it seem that this package that they provide might do the job:

https://github.com/CNES/aviso-fes/

Though at a quick look, It doesn't seem to do currents: only tidal heights.

I see this note on the web page:

"The FES2022 currents are not disseminated yet, they will be delivered to scientific teams and for scientific studies on demand. Please contact aviso@altimetry.fr if you are interested. Note that the FES2014 currents are now also delivered for any purpose under the standard license."

But the "legacy" version does seem to have currents -- presumably working with the FES2014 data.

https://github.com/CNES/aviso-fes/blob/legacy-c-version-archive/examples/fes_uv.py

I hope this helps -- I'm sorry we don't have a ready-to-go solution for this -- it does look very promising. But let us know if you pursue this, and we'll try to help with the PyGNOME integration part.

**Comment by Misiorama** [comment]
Thank you for your answers. I am very new to all this, and am a little lost on how to proceed. According to the above, I downloaded the product “FES2014a_currents” in two files: eastward_velocity and northward_velocity which contain 34 .nc files of tidal constituents with two variables each: ua and ug, and va and vg. 
Could you please guide me on how to calculate the tidal currents from these files? 

Sorry for the inconvenience, I really appreciate your help.

**Comment by ChrisBarker-NOAA** [comment]
Actually, we are new to this as well -- coincidentally, we learned about the FES project only recently. We have not yet developed code to work with it.

We would like to -- but I'm not sure when we might get around to it.

If you can get help turning the constituents into current velocities, we can help you get the results into a form PyGNOME can use. 

Does the FES project provide any kind of tech support, or more documentation?

**Comment by Misiorama** [comment]
The FES project does not provide much documentation on how to work with your data, at least from what I have read so far. At the moment I am running the script you have recommended, although it does not recognize the values or the .nc files. As soon as I have something done, I will surely ask you again for help. Thank you very much!

**Comment by ChrisBarker-NOAA** [comment]
Good luck! closing this issue for now -- feel free to re-open of start a new one if/when you have additional questions.
