### ISSUE TITLE
Can I see a weathering data, that affected by ice concentration.

### ISSUE THREAD

**Issue by tottorikenn** [NOAA-ORR-ERD/PyGnome#169]
Dear all.
I want to see weathering data in the high ice concentration environment.

start_x=30.960
start_y=77.928
x_min=28
x_max=33
y_min=76
y_max=79

import gnome.scripting as gs
import os
from gnome.model import Model
from gnome.weatherers import Evaporation, NaturalDispersion,Emulsification
from gnome.environment import Water, Wind, Waves

mapfile    = gs.get_datafile('ne_110m_coastline.bna')
mymap      = gs.MapFromBNA(mapfile) # no refloat
#mymap      = gs.MapFromBNA(mapfile, refloat_halflife=-1) # no refloat

start_time = gs.asdatetime("2009-05-14T00:00")
oil = gs.GnomeOil(filename="troll-blend_EX00051.json")
model = gs.Model(start_time=start_time,
                 duration=gs.days(8),
                 time_step=60 * 15, # 15 minutes in seconds
                 )
model.map = mymap
release_time = gs.asdatetime("2009-05-15T08:00")
spill = gs.surface_point_line_spill(num_elements=1000,
                                    start_position=(start_x, start_y),
                                    release_time=release_time,
                                    end_position=(start_x, start_y),
                                    end_release_time= release_time + gs.hours(1),
                                    amount=5000,
                                    substance=oil,
                                    windage_range=(0.025, 0.025),
                                    windage_persist=-1,
                                    name='My spill')
model.spills += spill

# ... add movers/weatherers
#add wind
wind ='data_stream-oper.nc'
w_mover = gs.GridWind.from_netCDF(wind)
''',time_offset=0,
                                  uncertain_duration=3.0 * 3600, uncertain_time_delay=0,
                                  uncertain_speed_scale=2.0, uncertain_angle_scale=0.4,
                                  scale_value=1, default_num_method='RK2'''
wind_mover= gs.WindMover(w_mover)
model.movers += wind_mover

#add current
current = 'interpolated_data_my_pc_4_renamed.nc'
#current = 'cmems_mod_arc_phy_my_topaz4_P1D-m_1731390185570_new.nc'
current_mover = gs.CurrentMover.from_netCDF(filename=current)
model.movers += current_mover

#add ice current
ice_aware_curr = gs.IceAwareCurrent.from_netCDF(filename=current)
ice_current_mover = gs.CurrentMover(ice_aware_curr)
model.movers += ice_current_mover

#add ice wind
ice_aware_wind = gs.IceAwareWind.from_netCDF(filename=wind,
                        ice_concentration=ice_aware_curr.ice_concentration,
                        ice_velocity=ice_aware_curr.ice_velocity
                        )
ice_wind_mover = gs.WindMover(ice_aware_wind)
model.movers += ice_wind_mover

#add weathering
#model = Model()
#wind = Wind(filename="path_2_file/mywind.txt")
waves = Waves(w_mover)
water = Water(temperature=300.0, salinity=35.0) #temperature in Kelvin, salinity in psu
model.weatherers += Evaporation(wind=w_mover,water=water)
model.weatherers += NaturalDispersion(waves=waves,water=water)
model.weatherers += Emulsification(waves)

model.outputters += gs.WeatheringOutput('weathering_with_ice')
model.full_run()

I use this code to see result.
When I run this code without ice_current_mover or ice_wind_mover, I saw this.
![weather_with_no_ice](https://github.com/user-attachments/assets/9a04b3d6-c677-4b03-894f-788c08b86a88)
After that, I add ice_current_mover or ice_wind_mover and I ran it.
![weather_with_ice](https://github.com/user-attachments/assets/21ce6df1-8b7c-45f4-a8a0-5bee493b1b6e)
I can't see any defference at those results.
I should add some environment objects of ice concentration?
I don't know how to add ice affection to weathering.
Please tell me someone how to make weathering simulation in high ice concentration environment.

Best regard.

**Comment by coconnor8** [comment]
You need to use the ice_aware_wind when you set up the weatherers and waves -
waves = Waves(ice_aware_wind)
model.weatherers += Evaporation(wind=ice_aware_wind,water=water)

And then you probably want either the ice aware wind and current or the non ice aware wind and current but not both.

**Comment by ChrisBarker-NOAA** [comment]
To be clear:

The way PyGNOME handles ice is to use the ice conditions to alter the environment, rather than the individual processes. So when using ice -- you want to use the "Ice Aware" environment objects everywhere -- and not use the "regular" objects at all. 

So:
`IceAwareWind` instead of Wind.
`IceAwareCurrent` instead of `Current`, etc ...

The `RandomMover` is both an Environment object and a Mover, so you want the `IceAwareRandomMover`.

But in all cases, you use either the "ICeAware" version, or the "regular" version, but not both.

-CHB

**Comment by tottorikenn** [comment]
Thanks coconnor8 and ChrisBarker.
I want to make sure clearly.
When I want to make ice environment simulation, I am forbidden to use regular those sentences?(I use those sentences in no ice simulation)
model.movers += current_mover
model.movers += wind_mover
and I have to use Iceaware something instead of those.
Is it right?
Best regard

**Comment by ChrisBarker-NOAA** [comment]
you need a current mover and a wind mover, but those movers need to be using a IceAwareWind and IceAwareCurrent:

for example, from your code above:

This is correct (assuming that the currents and ice info are in that netcdf file)

```
#add ice current
ice_aware_curr = gs.IceAwareCurrent.from_netCDF(filename=current)
ice_current_mover = gs.CurrentMover(ice_aware_curr)
model.movers += ice_current_mover
```
But you want only that, not this also:
```
#add current
current = 'interpolated_data_my_pc_4_renamed.nc'
current_mover = gs.CurrentMover.from_netCDF(filename=current)
model.movers += current_mover
```

Similarly for the Wind Mover.

**Comment by tottorikenn** [comment]
Thanks for your advice ChrisBarker.
I clearly understand.
