### ISSUE TITLE
functional tests  error

### ISSUE THREAD

**Issue by satlabs** [NOAA-ORR-ERD/PyGnome#17]
After building pygnome using Anaconda .when I try to run  set of unit and functional tests to make sure that py_gnome is working properly. I get an error message . Please find attached output error message .Please help to resolve this issue . Thank You .
![tests](https://cloud.githubusercontent.com/assets/16771192/12840824/8131bafa-cc0c-11e5-800d-6e550eb7c535.png)

**Comment by ChrisBarker-NOAA** [comment]
Yes, sorry about that -- there seems to be some incompatibility on Windows between py_gnome and the latest version of gdal.

Try downgrading gdal:

``conda install gdal=1.11``

**Comment by satlabs** [comment]
Thank You.

**Comment by Mandy1609** [comment]
I am having the exact same problem now with gdal v 2.2.2 , but I can't downgrade to gdal=1.11 since none of my channels seems to have it anymore. Any tips? I tried several channels but no success.

**Comment by ChrisBarker-NOAA** [comment]
Goal is no longer required for PyGNOME— try uninstalling it and see
what happens.

**Comment by Mandy1609** [comment]
to run the conftest.py it needs 'osgeo' module, which is part of gdal, isn't it?
![image](https://user-images.githubusercontent.com/69759387/91341327-63be4980-e7ea-11ea-8d76-023064f4e92c.png)

**Comment by Mandy1609** [comment]
Now I am getting the following. 

![image](https://user-images.githubusercontent.com/69759387/91343126-198a9780-e7ed-11ea-8e14-d37cf1331256.png)

**Comment by ChrisBarker-NOAA** [comment]
Make sure to pull a new copy of the code: gdal (osgeo) is not longer used in the develop or master branches.
