### ISSUE TITLE
beached spill does not refloat

### ISSUE THREAD

**Issue by fdongyu** [NOAA-ORR-ERD/PyGnome#21]
Dear GNOME developer,  I apologize for opening an issue here. 
I am using SUNTANS hydrodynamic model and NAM wind model to drive GNOME in Galveston Bay area. However, it doesn't appear that the beached spill will refloat. I have set the refloat_halflife to be one hour. 
I can confirm the land and water is specified correct in GNOME. Can you given me any hint of what problem might be? Thank you in advance.

**Comment by ChrisBarker-NOAA** [comment]
This is a great place to report issues!

First -- is this using the PyGnome code in this gitHub repository? Or the GNOME1 Desktop version?

Second -- we'll need more information about your configuration -- if it's possible to post your data files somewhere we can get them, and also your script or a save file from desktop GNOME, then we can figure out what's going on.

Also -- I"m curious -- I understand SUNTANS used a mixed triangular/quad grid -- how are you handling that with GNOME? converting to all triangles?

as for refloating -- when the elements "refloat", they are still subject to the movers -- so if the wind is blowing toward land, they will get re-beached right away -- is that possibly your issue?

**Comment by fdongyu** [comment]
Dr. Barker, Thanks a lot for the quick reply. 
1. Yes, I am using the PyGnome code in this repository.
2. I tested more cases, and you are correct. Particles that beached "forever" is due to wind keeping blowing towards land.  The issue should be closed. Thank you very much. 
3. I used SUNTANS triangular grid this time. For a mixed grid, as you said, I simply convert it to all triangles or interpolate on a uniform or curvilinear grid.

**Comment by ChrisBarker-NOAA** [comment]
glad you figured it out.

For the mixed triangle/quad grids -- we would like to support that directly at some point. Would you be interested in helping with that effort?

**Comment by fdongyu** [comment]
Absolutely. I am working with Dr. Ben Hodges on the Texas spills. Our operational system will be much improved if GNOME can use the triangle/quad grids. As you may have already known, the SUNTANS hybrid output is available here (http://barataria.tamu.edu:8080/thredds/catalog/QuadWide_2009/catalog.html).

**Comment by ChrisBarker-NOAA** [comment]
Are you picking up where Xianlong left off?

Why don't you send me a direct email, and we can start looking that this.

-CHB
