### ISSUE TITLE
Visualization of wind and current vectors/2D

### ISSUE THREAD

**Issue by amirheidari** [NOAA-ORR-ERD/PyGnome#35]
Dear friends,
Is there a method to visualize the wind and current velocity vectors in PyGnome, like Gnome.exe?

Regards
Payam

**Comment by ChrisBarker-NOAA** [comment]
The image outputter has some support for visualizing currents.

Stay tuned for some notes on that.

However, for interactive use and visualization, we are putting our efforts into the Web interface: WebGNOME.

You can run WebGNOME locally on your own machine:

https://github.com/NOAA-ORR-ERD/WebGnomeClient

And you can test it out with our preview version:

http://gnome-stage.orr.noaa.gov

**Comment by jay-hennen** [comment]
To create output images in PyGnome you would use a gnome.outputters.Renderer

A good example of usage is in script_columbia.py. Of note is line 55 for setting the viewport, and line 53 for actual instantiation of the object. You need to setup paths to the mapfile and images directory. See the script for an example of that

To view velocity vectors and grids in the output, you would use `Renderer.add_vec_prop(vecs)` during the model setup, where `vecs` is a GridCurrent or GridWind object. To view the grid, you would use `Renderer.add_grid(vecs.grid) where `vecs` is a GridCurrent/GridWind.

If you simply want to view the vectors however, and it is not important for output, using the web client as described above is a simpler solution

**Comment by amirheidari** [comment]
Hello mates,
The web client is really amazing. It is very nice and useful. I am sure it will be very popular in near future.
Actually my model,which is based on GNOME, is somehow sophisticated and I need to use the installed version. I tried this:
> fn = ('wind_final.nc')
> current_object = GridCurrent.from_netCDF(filename = fn)

but the program returns an error: ValueError: Units of m s**-1 are not supported

Do you know how can I solve this?

Sincerely,
Payam

**Comment by jay-hennen** [comment]
It's not a unit strig we recognize by default. You should be able to pass a units keyword argument to override what it reads from the file. 'm/s' or 'm s-1' or 'meters s-1' should all work.

**Comment by amirheidari** [comment]
Thank you dear Jay-hennen,
I modified the code as:
 > current_object = GridCurrent.from_netCDF(filename = fn, grid_topology={'node_lon':'lon','node_lat':'lat'}, units='m/s')

The problem with unit was solved. But now it returns the following error:
raise ValueError("Data/grid shape mismatch. Data shape is {0}, Grid shape is {1}".format(d.shape, self.grid.node_lon.shape))
ValueError: Data/grid shape mismatch. Data shape is (10224, 97, 193), Grid shape is (193,)

**Comment by jay-hennen** [comment]
The data file dimensions are ordered incorrectly. It looks like it's organized as (ele, depth, time), but it must be (time, depth, ele) to be compatible. 

You need to transpose the file so it has this ordering.

**Comment by amirheidari** [comment]
The data variables (u and v) have been defined as a function of (time, lat, lon). I have no elevation or depth in my datasets. So, the order seems to be correct. When I use .exe version, the vectors are shown well. 
Maybe  there is a problem with "grid"! Grid shape  defined based on longitude, whose size is 193. But is should also consider latitude, whose size is 97.
Should we define the grid manually?

**Comment by jay-hennen** [comment]
Wait, so you have 10224 time slices in your file? In that case I think the problem is that your grid variables (latitude and longitude) are only 1 dimensional. In other words, if your data has dimensions (time, x, y), then your latitude variable must have dimension (x, y), and the same with your longitude variable.

This is a recognized limitation in the code right now. All our use cases work with data that is not on orthogonal, rectilinear grids, which is all you can define if you have 1D longitude and latitude variables, so it has not been added yet.

In your case, you should probably define the grid manually. See below for details:

```
from gnome.environment.gridded_objects_base import Grid_S
from netCDF4 import Dataset
import numpy as np

d = Dataset(filename)
lon_var = d['lon'][:]
lat_var = d['lat'][:]
lon, lat = np.meshgrid(lat_var, lon_var)

g = Grid_S(node_lon = lon, node_lat = lat)
```

Then pass `g` as the `grid` keyword arg when doing GridCurrent.from_netCDF.

**Comment by amirheidari** [comment]
Yes. 10224 is time slice, and my latitude and longitude are one dimensional, like HYCOM current data files. 
I tried the above code. But the module gridded_objects_base does not exist in my package:
ImportError: No module named gridded_objects_base

I use windows version, and I installed the package about 8 months ago. In the .exe version both vectors and grids are shown very well!

**Comment by jay-hennen** [comment]
Oh, my bad! the first line should be:
`from gnome.environment.grid import Grid_S`

Sorry I forgot which version you were working with.

**Comment by amirheidari** [comment]
Thank you very much dear Jay-hennen,
I used SGrid from pysgrid (I don't have Grid_S):
                >from pysgrid import SGrid
                >d = Dataset('current_final.nc')
                >lon_var = d['lon'][:]
                >lat_var = d['lat'][:]
                >lon, lat = numpy.meshgrid(lon_var, lat_var)
                >g = SGrid(node_lon = lon, node_lat = lat) 
                >fn = ('current_final.nc')
               > current_object = GridCurrent.from_netCDF(filename = fn, grid=g, units='m/s')
It seems every thing is ok, but the following line returns an error:
              > Renderer.add_vec_prop(current_object)

TypeError: unbound method add_vec_prop() must be called with Renderer instance as first argument (got GridCurrent instance instead)

Do you know what is the problem?

**Comment by jay-hennen** [comment]
Renderer is the class type. As the error says, it needs to be called on an instance:
```
rend = Renderer([args])
rend.add_vec_prop(current_object)
model.outputters += rend
```

**Comment by amirheidari** [comment]
Dear Jay-hennen,
I corrected the code. Now grids are shown well. But, when visualizing the vectors the output is not clear. I have attached two outputs. Is it possible to adjust the size of vectors or make the output clear?

                > d = Dataset('wind_final.nc')
                > lon_var = d['lon'][:]
               >  lat_var = d['lat'][:]
               >  lon, lat = numpy.meshgrid(lon_var, lat_var)
                > g = SGrid(node_lon = lon, node_lat = lat)
              >   g.build_celltree()
                > current_object = GridCurrent.from_netCDF(dataset =d ,grid_topology={'node_lon':'lon','node_lat':'lat'},varnames=['u', 'v'], units='m/s', grid=g ) 
              >  rend = Renderer(mapfile, gulf_images_dir, size=(800, 600))
                > rend.add_vec_prop(current_object)
                
               > model.outputters += rend

![wind](https://user-images.githubusercontent.com/25119930/31492112-f2820b7a-af49-11e7-9fc9-23b9ef88ca60.png)
![current](https://user-images.githubusercontent.com/25119930/31492116-f5c7e4ee-af49-11e7-9d26-fbecb41ae24a.png)

**Comment by jay-hennen** [comment]
There's some options. Here's the function signature for add_vec_prop:

```
    def add_vec_prop(self, prop, on=True,
                     color='LE', mask_color='uncert_LE',
                     size=3, width=1, scale=1000):
```
I believe size will change the size of the dot, width the width of the line, and scale gets multiplied into the length of the vector. FYI, the currents flow _away_ from the dot, along the line.

**Comment by amirheidari** [comment]
Dear Jay-hennen,
Thank you very much for your support. It is now very good, although the vectors are something like dash, instead of arrow. 

Best Regards
Payam Amir-Heidari
