### ISSUE TITLE
Is it possible to run PyGnome using Jupyter Notebooks?

### ISSUE THREAD

**Issue by jwsvargas** [NOAA-ORR-ERD/PyGnome#36]
Hello!

I'm stating with PyGnome after a while on the desktop version. I found it very useful to work with Jupyter Notebooks, specially because I intend to fill the scripts with explanations and topics.

How can I use the notebook in the gnome environment? I tried to open it from the conda prompt from inside the environment, but id doesn't seem to work.

Thanks.

**Comment by ChrisBarker-NOAA** [comment]
WE use py_gnome with Jupyter all the time.

If you have a conda environment where py_gnome can be imported, then starting up a notebook from there should work fine.

what are you doing, and what errors are you getting?

-CHB

**Comment by jwsvargas** [comment]
Thanks for answering, Mr. Barker.

I am first activating the Gnome environment and then I'm launching jupyter notebook from there. I get the following error when I try to create the model>>>

`from gnome.model import Model`

_---------------------------------------------------------------------------_
_ImportError                               Traceback (most recent call last)_
_<ipython-input-1-33e57c684dc4> in <module>()_
_----> 1 from gnome.model import Model_

_ImportError: No module named gnome.model_


It can be a pretty basic problem, but since I'm new in Python coding I'm struggling a little bit.

Thanks again.

**Comment by ChrisBarker-NOAA** [comment]
That means the gnome package is not installed in the Python Jupiter is using.

Ether Jupiter is using s different environment, or gnome is not installed in your gnome environment.

Try starting s plain python interpreter and typing:

Import gnome

If that works, then Jupyter is not using the environment’s python.

Make sure that you have installed Jupyter into the gnome environment:

conda install jupyter 

Should do it.

**Comment by jwsvargas** [comment]
Hello!

It worked now. I had jupyter installed but not in the gnome environment, as you suggested.

Thank you very much!
