### ISSUE TITLE
Gnome.scripting: is there more info available?

### ISSUE THREAD

**Issue by jwsvargas** [NOAA-ORR-ERD/PyGnome#37]
Hello all!

This PyGnome thing is very exciting. I find it a way clever way of doing those simulations, mainly because everyone of them is a different challenge now. You've done a nice job there NOAA staff.

I've been trying to understand the difference between using a release function available at the _spill_ module and a helper function available at the _scripting_ utilities. Is there any? I mean, for instance, there is a _point_line_release_ in both of those modules. Which one should I use? And why there is a _GridRealease_ in the _spill_ module, but if I look for a uniform distribution I have to call the _scripting_ again?

Maybe because there's not enough documentation on the _scripting utilities_ section I am missing something.

Look to hear from you, guys. 
Cheers!

**Comment by jwsvargas** [comment]
Hello, Chris.

Thanks for the information. I agree with you that the documentation needs some work on it. However, it is actually very comprehensible, even for starters like me.

I'm working on a step-by-step notebook in order to provide an in-house documentation for people who will have to use PyGnome in my lab. I brought you those questions because my main concern would be if the user could access all functions available for a specific task (_e. g._ setting a spill) from only one module, in order not to require extensive knowledge of the code's utilities and their locations. It would be like looking at a specific place when looking for a specific thing. That's why I asked about release functions in different modules. Maybe that's something that could be worked on too, what do you think?

Thanks again for your support.

**Comment by ChrisBarker-NOAA** [comment]
> my main concern would be if the user could access all functions available for a specific task (e. g. setting a spill) from only one module, in order not to require extensive knowledge of the code's utilities and their locations.

Yes, that is the idea behind the scripting module. So if there is something missing that you need, let us know, and we'll put it there. Sound slike GridRelease is one.

I'll go add that now :-)
