### ISSUE TITLE
Tests fail, remote server is offline

### ISSUE THREAD

**Issue by yosoyjay** [NOAA-ORR-ERD/PyGnome#43]
I am attempting to validate a new installation, but the tests do not complete because the `data_server` (http://gnome.orr.noaa.gov/py_gnome_testdata/) defined in `py_gnome/gnome/utilities/remote_data.py` is offline.

**Comment by ChrisBarker-NOAA** [comment]
Sorry about that -- we reconfigured some things, and must have let that fall off the radar.

It should be back soon.

And most of the tests should run OK.

Though I suppose we should have a flag for running without the downloaded test data...

**Comment by yosoyjay** [comment]
Looks good now, thanks for the fix!
