### ISSUE TITLE
Problem running installation script

### ISSUE THREAD

**Issue by bobsurf00** [NOAA-ORR-ERD/PyGnome#46]
Hi,
I'm trying to install pyGnome on Windows 10 and have been following the instructions.  All good until running the setup script: 
python setup.py develop 
where I get an error:
![pygnome setup script screen grab](https://user-images.githubusercontent.com/45707327/49683695-e88f9e00-fb03-11e8-8e48-f7bb998a2d78.PNG)
Hopefully something simple.
Thanks and I look forward to hearing from you.
Regards
Rob

**Comment by JamesMakela-NOAA** [comment]
@bobsurf00: It looks the gitpython package can't find your git executable command.  I am not quite as familiar with Windows, but is it possible to add the git path to your users $PATH, or maybe setup the $GIT_PYTHON_GIT_EXECUTABLE for your user?

**Comment by ChrisBarker-NOAA** [comment]
Note that we are using git during setup to manage versioning for development -- we probably should re-write that to be usable without it. But in the meantime, you do need to have git installed in a way that it can be found.

I think the usual default isntall from:

https://git-scm.com/download/win

should work.

But Tortoise git may not, for example.

**Comment by bobsurf00** [comment]
Many thanks for your replies.  
Problem sorted - when I was installing git, I ticked the option that didn't install the path.  I reinstalled with the path and that seems to have done the trick.
So it looks as if pyGnome has installed correctly but when I do the tests, I get the following errors.
![pygnome setup script screen grab 2](https://user-images.githubusercontent.com/45707327/49706621-e6435600-fc61-11e8-8309-600636787269.PNG)
Any ideas? Let me know of you need further information.
Thanks again
Rob

**Comment by ChrisBarker-NOAA** [comment]
That is the error you would get if you had not built py_gnome before running the tests. (Or the build failed)

Did you run `setup.py install` or `setup.py develop` ?

and did that seem to run successfully?

**Comment by bobsurf00** [comment]
I ran setup.py develop and it seemed to run successfully.

Just re-ran with the following result:

![pygnome setup script screen grab 3](https://user-images.githubusercontent.com/45707327/49804198-ef7d1180-fd8c-11e8-9ae6-88e59fe4810f.PNG)

**Comment by ChrisBarker-NOAA** [comment]
OK -- I just looked, and indeed there is a missing file in gitHub master -- no idea how that could have happened, but I"ll update that soon.

Sorry about that.

-CHB

**Comment by ChrisBarker-NOAA** [comment]
OK -- I've pushed an update to the master branch.

All tests are passing for me.

I hope this works better for you.

**Comment by bobsurf00** [comment]
Thanks Chris - this works now and all installed.  
Having said that, on the tests I appear to fail four.  For py.test:
![capture pygnome tests](https://user-images.githubusercontent.com/45707327/49873212-4ac70680-fe56-11e8-8ebc-044d81a342bb.PNG)
and for py.test --runslow
![capture pygnome tests runslow](https://user-images.githubusercontent.com/45707327/49873670-6a126380-fe57-11e8-8a57-02303b477172.PNG)
Is this normal?

**Comment by ChrisBarker-NOAA** [comment]
Actually, no failures, but four that passed that we didn't expect to pass. Which we shold investigate. But you're good to go :-)

**Comment by ChrisBarker-NOAA** [comment]
Thanks for the report, and sorry for the hassle

**Comment by bobsurf00** [comment]
Many thanks for the support, Chris
