### ISSUE TITLE
Full trajectories/paths in netcdf output

### ISSUE THREAD

**Issue by daf** [NOAA-ORR-ERD/PyGnome#5]
Hi all,

I noticed that the WebGnomeAPI/Client projects allow you to download a zip file of your model run, containing two .nc files - both appear to be finishing positions (last timestep) of each particle in the simulation.  Code to generate that [appears to be here](https://github.com/NOAA-ORR-ERD/PyGnome/blob/c87da4386787a50e07e49005deb300b854d6c834/py_gnome/gnome/model.py#L1088-L1112).

Ultimately, we'd like a trajectory for each particle over the entire model run, not just the single timestep.  I'm assuming this is not possible now, but wondering what kind of modifications can be done to support such a thing.  I'm thinking it involves executing a similar method to `_save_spill_data` every time a timestep is computed.

Thoughts?

**Comment by ChrisBarker-NOAA** [comment]
On Aug 20, 2015, at 1:21 PM, Dave Foster <notifications@github.com> wrote:
I noticed that the WebGnomeAPI/Client projects allow you to download a zip
file of your model run, containing two .nc files - both appear to be
finishing positions (last timestep) of each particle in the simulation.
Code to generate that appears to be here
<https://github.com/NOAA-ORR-ERD/PyGnome/blob/c87da4386787a50e07e49005deb300b854d6c834/py_gnome/gnome/model.py#L1088-L1112>
.

Ultimately, we'd like a trajectory for each particle over the entire model
run, not just the single timestep. I'm assuming this is not possible now,

Sure it is :-)

Look for the netcdf outputter: I think in

gnome.outputters.netcdf

There may not yet be a hook in the API to get that yet, but it shouldn't be
too hard to add, and we want that anyway.

-Chris

but wondering what kind of modifications can be done to support such a
thing. I'm thinking it involves executing a similar method to
_save_spill_data every time a timestep is computed.

Thoughts?

—
Reply to this email directly or view it on GitHub
<https://github.com/NOAA-ORR-ERD/PyGnome/issues/5>.

**Comment by daf** [comment]
Ok, I've figured my way around enough to adjust - I made a JavaScript `NetCDFOutputter` and added it to the [default outputters in WebGnomeClient](https://github.com/NOAA-ORR-ERD/WebGnomeClient/tree/master/js/model/outputters), removed [these lines in outputter/netcdf.py](https://github.com/NOAA-ORR-ERD/PyGnome/blob/9be5736be8603cce954e0b78fbf8eef5fd5c26eb/py_gnome/gnome/outputters/netcdf.py#L587-L588) (due to the super call setting that flag to False), and managed to get an .nc file with full timesteps.  The former is a likely need in the codebase, the latter needs to happen but not sure the correct approach to make that change.

Is the format fully decided? I was expecting multi-dimensional variables like lat/lon, dimensioned likely by particle id - that's a bit more self-describing.

**Comment by daf** [comment]
For instance, here's larvamap's format (posted mostly for the dimensions)

```python
        time = nc.createVariable('time', 'i', ('time',))
        part = nc.createVariable('particle', 'i', ('particle',))
        depth = nc.createVariable('depth', 'f', ('time', 'particle'))
        lat = nc.createVariable('lat', 'f', ('time', 'particle'), fill_value=fillvalue)
        lon = nc.createVariable('lon', 'f', ('time', 'particle'), fill_value=fillvalue)
        salt = nc.createVariable('salt', 'f', ('time', 'particle'), fill_value=fillvalue)
        temp = nc.createVariable('temp', 'f', ('time', 'particle'), fill_value=fillvalue)
        u = nc.createVariable('u', 'f', ('time', 'particle'), fill_value=fillvalue)
        v = nc.createVariable('v', 'f', ('time', 'particle'), fill_value=fillvalue)
        w = nc.createVariable('w', 'f', ('time', 'particle'), fill_value=fillvalue)
        settled = nc.createVariable('settled', 'f', ('time', 'particle'), fill_value=fillvalue)
        dead = nc.createVariable('dead', 'f', ('time', 'particle'), fill_value=fillvalue)
        halted = nc.createVariable('halted', 'f', ('time', 'particle'), fill_value=fillvalue)
```

**Comment by daf** [comment]
@kwilcox explains this is the [CF DSG "Collection of Trajectories"](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/aphs04.html)

**Comment by ChrisBarker-NOAA** [comment]
@daf 

The format it pretty set. It was developed as the result of a discussion with a number of other particle tracking modellers (mostly oil spill), including a couple folks from ASA (weren't you on that list?)
It seem more complicated than it should be, but that's to accommodate models that create and destroy particles as the model runs -- and, as a rule, you don't know how many will be created. So a 2-d time, particle_num) array won't work. This format follows the CF recommendations for "ragged arrays".

We've got some code for working with it here:

https://github.com/NOAA-ORR-ERD/GnomeTools/blob/master/post_gnome/post_gnome/nc_particles.py

It was designed to make it easiest (and most efficient) to query information about all the particles at a particular time, rather than tracking a single particle over time.

As it happens, if the number of particles is constant, the arrays can be re-shaped to a 2-d array trivially (at least in numpy :-) )

**Comment by ChrisBarker-NOAA** [comment]
BTW,

The CF idea of a "trajectory" wasn't well suited to this type of model -- really more designed for the trajectory of, say, a glider -- a focus on a one ting moving through space with time, rather than a collection. But the main issue was the number of particles changing over time.

I've been meaning to write up all this, with teh motivation and capture the discussion, but haven't found the roundtoits yet ...

**Comment by daf** [comment]
Yes that makes sense, sorry!  I hadn't been thinking of continuous spills/numbers of particles changing.  I may have been on mailing list but don't remember.  I'm much more focused on software engineering anyway so likely didn't have much to contribute to that discussion.

Format aside, we'll still want to export every timestep, and I'm not sure how to do that without removing [these lines](https://github.com/NOAA-ORR-ERD/PyGnome/blob/9be5736be8603cce954e0b78fbf8eef5fd5c26eb/py_gnome/gnome/outputters/netcdf.py#L587-L588).  My first thought is making a configurable flag you pass to the `NetCDFOutput` class, something like `output_every_timestep` - which seems like it might actually fit as another value of the `which_data` parameter.  Any thoughts here?

**Comment by ChrisBarker-NOAA** [comment]
Check the output_timestep parameter -- if set to None, it should output
every timestep.

This is the same for all outputters.

Chris



Sent from my iPhone

On Aug 25, 2015, at 11:22 AM, Dave Foster <notifications@github.com> wrote:

Yes that makes sense, sorry! I hadn't been thinking of continuous
spills/numbers of particles changing. I may have been on mailing list but
don't remember. I'm much more focused on software engineering anyway so
likely didn't have much to contribute to that discussion.

Format aside, we'll still want to export every timestep, and I'm not sure
how to do that without removing these lines
<https://github.com/NOAA-ORR-ERD/PyGnome/blob/9be5736be8603cce954e0b78fbf8eef5fd5c26eb/py_gnome/gnome/outputters/netcdf.py#L587-L588>.
My first thought is making a configurable flag you pass to the NetCDFOutput
class, something like output_every_timestep - which seems like it might
actually fit as another value of the which_data parameter. Any thoughts
here?

—
Reply to this email directly or view it on GitHub
<https://github.com/NOAA-ORR-ERD/PyGnome/issues/5#issuecomment-134623055>.

**Comment by daf** [comment]
Excellent - I had misread the code.  Getting local output just fine now.
