### ISSUE TITLE
Building PyGnome  Error Fatal Netcdf in linux

### ISSUE THREAD

**Issue by Lemcastroro** [NOAA-ORR-ERD/PyGnome#56]
Hi everyone!

I have tried to build pygnome in Linux but when I put "python setup.py develop" I get this error:

`../lib_gnome/TimeGridVel_c.cpp:17:10: fatal error: netcdf.h: No existe el archivo o el directorio
   17 | #include "netcdf.h`
 
I have already verified that the netcdf4 library is installed

![Captura_error](https://user-images.githubusercontent.com/49490229/87121684-ec882280-c248-11ea-8efc-760459a1759e.PNG)

and I don't know if there is something else that I am missing.

Thanks for your help :)

**Comment by ChrisBarker-NOAA** [comment]
We'll have to look closer on Linux, but first: how is netcdf4 installed? if installed with the system package manager, is the "-devel" version of the package installed? often Linux packages the headers, etc needed for compiling separately from the library itself.

Also, in case it matters: what distro and version are you using?

**Comment by Lemcastroro** [comment]
I checked everything and it had been a problem to bind the compiler with the path of the includes.

Thanks for the help 👍

**Comment by ChrisBarker-NOAA** [comment]
You've got it working now?

BTW, we have a Python 2 and 3 compatible version going -- it's not quite fully working (48 tests fail) but if you want to check it out, it's in the "py23" branch.

We are aiming for "pyhon 3 code that runs on python2" at this point.

**Comment by Lemcastroro** [comment]
Yes, I have it working right now.

Interesting! I'll check it out. 

Could you tell me what these failed tests correspond or are related to?

Thanks :)

**Comment by ChrisBarker-NOAA** [comment]
We haven't fully investigated the failed tests yet, but at least some of them seem to be in the code that interpolates gridded data :-(

-CHB
