### ISSUE TITLE
ImportError: No module named gnome

### ISSUE THREAD

**Issue by bobsurf00** [NOAA-ORR-ERD/PyGnome#57]
Hi Chris et al.

I'm getting back into pygnome and have run into an issue when running the test scripts with the following error:

ImportError: No module named gnome

Strange thing is that I've run the tests successfully before.  Hopefully something simple.  Any ideas?

Thanks

Rob

**Comment by ChrisBarker-NOAA** [comment]
it must not be installed into the environment you are running Python in.

make sure you ran an install command in the same environment you are using.

If you did do that, maybe you aren't in the environment you think you are?

**Comment by bobsurf00** [comment]
Hi Chris,

 

I decided to reinstall py_gnome but now having all sorts of troubles.

 

I set up the channels and Python environment ok but when it came to installing the conda requirements (conda install --file conda_requirements.txt

) I seemed to be getting a lot of conflicts (see attached).

 

I then tried to install the oil library and also received lots of errors (attached).

 

Thanks in advance for any help you may be able to provide.

 

Best regards

 

Rob

**Comment by jay-hennen** [comment]
What version of conda are you using? I received similar conflicts until I
totally re-installed conda to the latest version. I think I was stuck on
conda 4.6.x or something and it was unable to update itself due to these
sort of conflicts so eventually I just had to start from scratch. It works
great now though.

**Comment by ChrisBarker-NOAA** [comment]
@jay-hennen's right, sometimes you just need to start from scratch again. I've come around to the idea that this isn't a failure -- it's how conda works best. Ideally, you create a complex environment afll at once, from scratch. You also ideally dont touch the root environment for anythiogn other than conda itself.

But before you try a new conda install, try this:

conda create -n gnome --file conda_requirements.txt

That creates a new environment from scratch, with the requirements file. So there won't be any conflicts with anything else you already have installed.

Good luck!

**Comment by bobsurf00** [comment]
Thanks for your replies – I reinstalled from scratch and think I’ve made some progress in that the dependencies installed, however, now have the following issues:

 

1.	Oil Library wont install (see below).  I suspect this is something to do with my system.

 



 

2.	After building pygnome the tests don’t seem to work (see attached)

 

Any ideas?

 

Thanks

 

Rob

**Comment by bobsurf00** [comment]
Hi guys – further to my email below I actually reset my machine to really start from scratch, however, unfortunately I still get the “permission denied” error when trying to install the Oil Library.  

 

I feel it’s something to do with the path setup for python but I followed the default instructions for Anaconda installation.

 

Grateful for any suggestions.

 

Thanks

 

Rob

 

**********************************************************************

 

 

Thanks for your replies – I reinstalled from scratch and think I’ve made some progress in that the dependencies installed, however, now have the following issues:

 

1.	Oil Library wont install (see below).  I suspect this is something to do with my system.

 



 

2.	After building pygnome the tests don’t seem to work (see attached)

 

Any ideas?

 

Thanks

 

Rob

 

 

From: rob.phillips@iinet.net.au <rob.phillips@iinet.net.au> 
Sent: Tuesday, 21 July 2020 1:41 PM
To: 'NOAA-ORR-ERD/PyGnome' <reply@reply.github.com>; 'NOAA-ORR-ERD/PyGnome' <PyGnome@noreply.github.com>
Cc: 'bobsurf00' <rob.phillips@iinet.com.au>; 'Author' <author@noreply.github.com>
Subject: RE: [NOAA-ORR-ERD/PyGnome] ImportError: No module named gnome (#57)

 

Hi Chris,

 

I decided to reinstall py_gnome but now having all sorts of troubles.

 

I set up the channels and Python environment ok but when it came to installing the conda requirements (conda install --file conda_requirements.txt

) I seemed to be getting a lot of conflicts (see attached).

 

I then tried to install the oil library and also received lots of errors (attached).

 

Thanks in advance for any help you may be able to provide.

 

Best regards

 

Rob

**Comment by ChrisBarker-NOAA** [comment]
though you can reply to these via email, it's better to go to gitHub and post thete, as you dont get all the cruft of quotes messages, etc.

So I can't wuote tell where you are at now. But I do see:

> LookupError: unknown encoding: cp65001

Encoding are a pain in the @$$, particularly on Windows. If you google this error, you'll see issues with it and Python 2 in other contexts. So this is not a GNOME problem. I think the issue is that your system is set up to use an encoding that Python does not know how to deal with.

I don't know how to reset your Windows system encoding, but maybe some googling will help there.

Sorry to not be more helpful :-(
'
'

**Comment by bobsurf00** [comment]
Sorry Chris - I can see the above get confusing when you reply to the emails.  

Ok so this is where I have got to: everything seems to work but for some reason I can't install the oil library as I don't seem to be able to run python from git.  It returns "permission denied".

![OilLibrary Git Error](https://user-images.githubusercontent.com/45707327/88374401-49004b80-cdcc-11ea-94af-89c801b8d172.PNG)

**Comment by bobsurf00** [comment]
I've solved this issue = the path for python was set up incorrectly.  See [https://stackoverflow.com/questions/56974927/permission-denied-trying-to-run-python-on-windows-10]

**Comment by ChrisBarker-NOAA** [comment]
Thanks for teh report, glad you got it resolved.
