### ISSUE TITLE
CatsMover with Tide doesn't serialize correctly

### ISSUE THREAD

**Issue by daf** [NOAA-ORR-ERD/PyGnome#6]
#### Context:
Trying to serialize a model (trajectory only, so far) and reconstitute it later so we can run models in the background via celery.  (working with proposed fix noted below!)

#### Issue:
The `filename` field of a [`Tide` object](https://github.com/NOAA-ORR-ERD/PyGnome/blob/9be5736be8603cce954e0b78fbf8eef5fd5c26eb/py_gnome/gnome/environment/tide.py#L82) inside of a `CatsMover` isn't serialized with its full path like it is inside of the `CatsMover` parent.

Tracing the calls and playing with IPython, I found the codepath it takes.  I expected any `Serializable` to continue to call `.serialize()` on any child `Serializable`, but it seems to short-circuit with `.to_dict()` instead.  Therefore, [`Tide.serialize`](https://github.com/NOAA-ORR-ERD/PyGnome/blob/9be5736be8603cce954e0b78fbf8eef5fd5c26eb/py_gnome/gnome/environment/tide.py#L208-L216), which is supposed to fix this attribute, is never called.

Looking back a bit in history for the `Serializable` class, I see that [`Serializable.to_dict`](https://github.com/NOAA-ORR-ERD/PyGnome/blob/9be5736be8603cce954e0b78fbf8eef5fd5c26eb/py_gnome/gnome/utilities/serializable.py#L602) used to take a `json_` parameter ([and is still documented that it does](https://github.com/NOAA-ORR-ERD/PyGnome/blob/9be5736be8603cce954e0b78fbf8eef5fd5c26eb/py_gnome/gnome/utilities/serializable.py#L614-L620)), but does not anymore as of 671499d4 when a bunch of things were refactored.

I am able to circumvent this by adding a `Tide.filename_to_dict`, which is a helper that [`Serializable.attr_to_dict` calls](https://github.com/NOAA-ORR-ERD/PyGnome/blob/9be5736be8603cce954e0b78fbf8eef5fd5c26eb/py_gnome/gnome/utilities/serializable.py#L640-L648) - I am not sure this is the correct solution for all cases, though, as we've lost the `json_` param and the (uncalled) `Tide.serialize` method only does that fixup when `json_='save'`, although I don't why.  If this is an acceptable fix I'll PR it:

```python
class Tide(Environment, Serializable):
    ...
    def filename_to_dict(self):
        return self.cy_obj.path_filename
```

This is only for when the model is serialized with `json_=webapi`, aka the default.  `save` has a different but similar issue.

**Comment by ChrisBarker-NOAA** [comment]
@daf,

We're looking into this, something does seem to have gotten a bit messed up in the refactor.

But I think you want to use "save" mode for this use-case anyway, rather than "webapi" mode -- save mode os for saving and reconstituting, after all. 

And if this is for celery / testing,  @NathanWilkins-NOAA may be able to help...

-CHB

**Comment by JamesMakela-NOAA** [comment]
@daf,

There are two contexts in which we serialize/deserialize objects.
- for generating a save file (json_='save')
- for serving objects to/from a web server (json_='webapi')

So the underlying issue which drove our decision to have these contexts is web security.
In a web server environment, the filename we would pass to a Tide object upon creation is the local location of a tide file on the machine that is running the web server.
And if we were paranoid, we wouldn't want to give any information to a web client that would betray the underlying filesystem structure of the web server.

So my question to you is will you be functional if you use the 'save' context?  I haven't worked all that much with Celery, but if you create save files from your model and pass them to your queue, it seems you should be able to reconstitute them on a worker.

(Oh, yeah.  We will definitely need to fix the docstrings in Serializable.  Sorry about that.)

**Comment by daf** [comment]
@JamesMakela-NOAA thanks, this explanation for the different `json_` parameters makes sense.

Unfortunately `serialize(json_='save')` loses information for a `CatsMover` object - I haven't investigated the full `Model` in detail because I knew this one to be problematic.  The `tide` attr is completely missing from the `serialize(json_='save')` output:

```python
In [7]: cm.serialize(json_='save')
Out[7]: 
{'active_start': '-inf',
 'active_stop': 'inf',
 'down_cur_uncertain': -0.3,
 'filename': u'/home/daf/dev/WebGnomeAPI/location_files/san_diego_bay/san_diego_bay_save/Tides.cur',
 'json_': u'save',
 'left_cur_uncertain': -0.1,
 'name': u'CatsMover',
 'obj_type': u'gnome.movers.current_movers.CatsMover',
 'on': True,
 'right_cur_uncertain': 0.1,
 'scale': True,
 'scale_refpoint': (-117.23, 32.681667, 0.0),
 'scale_value': 1.0,
 'uncertain_duration': 48.0,
 'uncertain_eddy_diffusion': 10000.0,
 'uncertain_eddy_v0': 0.1,
 'uncertain_time_delay': 0.0,
 'up_cur_uncertain': 0.3}
```

compare this to the output for `serialize()` (aka `json_=webapi`): (NOTE this includes my patch to adjust `tide.filename` to be a full path - the `CatsMover.filename` was always a full path)

```python
In [6]: cm.serialize()
Out[6]: 
{'active_start': '-inf',
 'active_stop': 'inf',
 'down_cur_uncertain': -0.3,
 'filename': u'/home/daf/dev/WebGnomeAPI/location_files/san_diego_bay/san_diego_bay_save/Tides.cur',
 'id': u'ed2996d4-523a-11e5-8001-b8ac6f829e5f',
 'json_': u'webapi',
 'left_cur_uncertain': -0.1,
 'name': u'CatsMover',
 'obj_type': u'gnome.movers.current_movers.CatsMover',
 'on': True,
 'right_cur_uncertain': 0.1,
 'scale': True,
 'scale_refpoint': (-117.23, 32.681667, 0.0),
 'scale_value': 1.0,
 'tide': {'filename': u'/home/daf/dev/WebGnomeAPI/location_files/san_diego_bay/san_diego_bay_save/TidesShio.txt',
  'id': u'ed28e180-523a-11e5-8001-b8ac6f829e5f',
  'json_': u'webapi',
  'name': u'TidesShio.txt',
  'obj_type': u'gnome.environment.tide.Tide',
  'scale_factor': 1.0},
 'uncertain_duration': 48.0,
 'uncertain_eddy_diffusion': 10000.0,
 'uncertain_eddy_v0': 0.1,
 'uncertain_time_delay': 0.0,
 'up_cur_uncertain': 0.3}
```

The two missing keys are `id` and `tide`.

When you deserialize, you'll get the `CatsMover` with a `tide=None` back.

This was the other issue I hinted at in my original issue text but of course forgot to file another issue for, but I guess it really just belongs in this issue!

> (Oh, yeah. We will definitely need to fix the docstrings in Serializable. Sorry about that.)

My brain automatically ignores most docstrings because I never believe them to be up to date!  I only mentioned it here as evidence that a refactor happened at one point that adjusted the behavior I'm seeing.

**Comment by daf** [comment]
@JamesMakela-NOAA,

There are a few instances where a `webapi` serialized model has full paths:

![2015-09-03-08 56 58](https://cloud.githubusercontent.com/assets/228715/9658930/0afb1824-521b-11e5-924a-b8404e88c460.png)

This is the model that made it to the client side which has a full path.

**Comment by ChrisBarker-NOAA** [comment]
Thanks for the diagnostics -- I think "id" is missing because we don't want to persist that. IN theory, one could load up the same save file twice, and we wouldn't want the id to be the same in those two instances.

The missing tide is a bug -- that certainly needs to get saved!

-Chris

**Comment by JamesMakela-NOAA** [comment]
@daf,

Yes, it appears we have a bug with the Tide.serialize() when we use the 'save' context.  It shouldn't be too hard to fix, and I will get something pushed out right away.

Regarding the full path attribute in the web client, could you give me a quick list of steps to reproduce this please?

**Comment by daf** [comment]
> Regarding the full path attribute in the web client, could you give me a quick list of steps to reproduce this please?

As simple as doing a Load Location - have inspector/webtools/whatever open, and check the model GET's response right after the location requests - there will be a full path in one of the movers inside of the model.

**Comment by JamesMakela-NOAA** [comment]
Hello @daf,

I resolved the CatsMover/Tide serialization issues last week, and today we updated the GitHub master for our projects.  So if you grab the new master branch, you should get fixes for these issues.
A short list of issues:
- For the serialization of Tide inside CatsMover, see d41558ac54eaf9e5a44a197803b6b2b7ba7acade
- For the issues concerning full paths, see 20b28e2d46148196d2c0b78f389102eb31423c06

I hope this resolves these issues for you.  Let me know and I can close this particular issue.

James

**Comment by daf** [comment]
Thank you @JamesMakela-NOAA , I'm just leaving on vacation and will not be able to validate until Tuesday.  I will close now and re-open as necessary as the intent is clearly there.

**Comment by daf** [comment]
Works! :+1: thank you!
