### ISSUE TITLE
test.py fails

### ISSUE THREAD

**Issue by Mandy1609** [NOAA-ORR-ERD/PyGnome#62]
Hi,
hope you can help with that.

I downloaded PyGnome version 0.6.1, then installed all required packages for Python environment version 2.7 with 
"conda install --file conda_requirements.txt" - without problems.
 
Following I built py_gnome with "python setup.py develop" (I am operating on Windows 10). No problem.

Now I ran "py.test" as:
(gnome) C:\Users\m.mueller\Anaconda3\GNOME\PyGnome-0.6.1\py_gnome\tests\unit_tests>py.test

and get the following error as per screenshot. No idea what I have done wrong??? Could you point me in the right direction please?

![image](https://user-images.githubusercontent.com/69759387/90395507-b5a5f780-e0a5-11ea-84ce-ebab8b42351d.png)

**Comment by ChrisBarker-NOAA** [comment]
This is a Windows Encoding issue that isn't really anything to do with PyGNOME :-(

Google: "python unknown encoding cp65001" and you'll see a lot of hits :-(

However, it looks like conda is supposed to have a work-around for this:

https://hang-hu.github.io/python/2017/07/27/Python-Unknown-Encoding-cp65001.html

https://github.com/conda/conda/issues/5448

Try restarting the shell (Command Prompt) and see if it works better -- ti's supposed to get fixed when conda "activates" the environment. 

If that doesn't work, then you can try making a conda environment for gnome, and then use that:

conda create -n gnome --file conda_requirements.txt

then

conda activate gnome

then:

python setup.py develop

then try the tests again.

Sorry this is such a pain :-(

-CHB

**Comment by ChrisBarker-NOAA** [comment]
Darn: I just looked closer at your error -- you are using an environment -- :-(

Maybe this will help:

https://github.com/conda/conda/issues/5448

Also: do make sure to update conda:

``conda update conda``

https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-conda.html

**Comment by Mandy1609** [comment]
This simple Windows Setting fixed it for me: 
https://github.com/conda/conda/issues/8327

Thanks for the help.
