### ISSUE TITLE
No module named map

### ISSUE THREAD

**Issue by egiraldof** [NOAA-ORR-ERD/PyGnome#66]
Hello, 

I have the following error when I try to run an example after installing the model on Windows: No module named map.

![image](https://user-images.githubusercontent.com/64181788/92042583-2143c200-ed40-11ea-9ebf-4cd16134177a.png)

I would appreciate any help to fix this error.

**Comment by jay-hennen** [comment]
This was recently reorganized. The new location of MapFromBNA is gnome.maps.map
