### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by fSohrabi75** [NOAA-ORR-ERD/PyGnome#67]

**Comment by coconnor8** [comment]
The old desktop GNOME can only take netcdf3 files so you would
need to convert the file before loading it in. You also may need to
change some of the dimension and variable names to match GNOME's
file format.

**Comment by farzanehashemabadi** [comment]
> The old desktop GNOME can only take netcdf3 files so you would
> need to convert the file before loading it in. You also may need to
> change some of the dimension and variable names to match GNOME's
> file format.

Thank you very much for your response. I have installed Gnome1.3.11, is that old version?

**Comment by coconnor8** [comment]
Yes, the new version is online at gnome.orr.noaa.gov. You might
want to try your scenario there.

**Comment by farzanehashemabadi** [comment]
@coconnor8 
Thank you, but I double checked orr.noaa.gov and the latest version of GNOME is 1.3.11 that already I used that one.

**Comment by coconnor8** [comment]
Sorry, I wasn't clear in my response. Gnome 1.3.11 is the latest desktop Gnome, but
we have moved Gnome online (WebGnome) which you can find and use at gnome.orr.noaa.gov .
Your wind file should work in the new WebGnome but you will need to update your variable
and dimension names to match the Gnome file format.

**Comment by farzanehashemabadi** [comment]
@coconnor8 
Which dimension is wrong? Time?

**Comment by coconnor8** [comment]
The main thing I noticed was the variables u10 and v10 should be
air_u and air_v. You can look at the file format documentation to
see if there are any other discrepancies.

**Comment by ChrisBarker-NOAA** [comment]
Thanks for the cleanup!
