### ISSUE TITLE
Use conda2 or 3 to install PyGnome

### ISSUE THREAD

**Issue by farzanehashemabadi** [NOAA-ORR-ERD/PyGnome#68]
Dear all,

can i install PyGnome with Anaconda3?

**Comment by ChrisBarker-NOAA** [comment]
PyGNome is still Python 2 only.

However, we are working on a Python 3 version, you can find it in the "py23" branch. (so named as this code should run under both python2 and 3)

It is currently "mostly" working, but not quite.

IF you would like to help debug it and report issues, I encourage you to give it a trty. But if you don't want to be on the "bleeding edge", python2 is still the way to go.

Note that you can create a Python2 environment under Anaconda 3 -- so no need to change anything else you are doing.

**Comment by ChrisBarker-NOAA** [comment]
Feel free to reopen this issue if you have other questions.

**Comment by farzanehashemabadi** [comment]
Thank you for your helpful response. Yes, I'm very interested in debugging it, and I'll be in touch with you whenever I do.
