### ISSUE TITLE
Biodegradation scheme 

### ISSUE THREAD

**Issue by vic1309** [NOAA-ORR-ERD/PyGnome#71]
Dear all

I'm a beginner user and I'm struggling a little bit to understand the biodegradation scheme, specifically about 'sara_type' and the determination of K. Some oils (e.g. oil_crude in sample oils) don't present a type classification, as required to use the function get_K_comp_rates. Others, on the other hand, have many component types (and boiling points). Regarding the latter case, is the entire _type_and_bp_ array considered on `def get_K_comp_rates`?   

Thank you for the support.

Cheers

**Comment by ChrisBarker-NOAA** [comment]
As you've closed this, I take you've figured it out.

But I want to note that the biodegradation algorithm is still experimental -- it has not been well tested and may change in the future.

Also -- we will probably refactor the OIl object to have degradation rates explicitly for each Pseudo component, rather than storing the SARA type and getting it from there.

**Comment by rmogollon** [comment]
Hello,

I am having some issues regarding Dissolution and/or Biodegradation. When activated, the same error appears:
AttributeError: 'GnomeOil' object has no attribute 'sara_type'

I am using a compatible oil type (diesel-2002_EC00567.json) and I think all the attributes are in there, however, I am not sure what is missing. Could anyone give me a hint about it?

Thanks

Rodrigo M.

**Comment by ChrisBarker-NOAA** [comment]
Both Dissolution and biodegradation haven't been actively maintained recently -- they need to be updated to match the latest GnomeOIl structure -- which no longer is based on SARA types.  

The best I can say is that they won't be usable without some work, and I'm not sure when we'll be abel to get that -- it's on the ToDo list, but not at the top :-(
