### ISSUE TITLE
PyWindMover and PyCurrentMover NetCDF not making the particles move?

### ISSUE THREAD

**Issue by moisespr123** [NOAA-ORR-ERD/PyGnome#74]
Hi,

I'm trying to use some global netCDF files to pass them to PyGnome's PyWindMover and PyCurrentMover functions. My code looks like this:

```
model.movers += gs.PyWindMover(wind_mover_nc_file)
model.movers += gs.PyCurrentMover(curr_mover_nc_file)
```

The NetCDF files are properly formatted according to the documentation with the Wind file containing the following variables:

```
lat
lon
time
air_u
air_v
```

Respectively, the Current file follows this format changing air_u and air_v to current_u and current_v.

The problem is that the spill particle never moves across timesteps, but using a RandomMover does makes the particles move. All I can see is the tiny black dot in the generated images while with the RandomMover object the spill grows at every timestep. Hence, I'm wondering if there's something I may be missing with formatting these netCDF files for our use case as they appear to not be working.

Do the timestep in the `time` variable need to match with the timesteps in PyGnome? The files are also formatted from 0-360. Do I need to slice the data to just pass the desired lat/lon range that we want to use? or should a Global file work fine?

 Thanks!

**Comment by jay-hennen** [comment]
You need to keep the same lon range for all the parts of your model, because there's no compensation for differing coordinate frames. So if you can only get data in 0-360, it's probably best to try and do your spill and map in that as well.

I think there are some arguments that you can use to compensate for this sort of discrepancy during setup, but I need to look them up. The most foolproof way is to make sure they're all in the same coordinate frame.

**Comment by ChrisBarker-NOAA** [comment]
I think Jay answered your question but:

"Do the timestep in the `time` variable need to match with the timesteps in PyGnome?"

no -- the time range has to match (of course) but PyGNOME will interpolate in time as needed.

Also: to test this -- use a no-land map (the default) and put your spill in 0-360 longitude coordinates. It should move with the currents.

**Comment by moisespr123** [comment]
Thank you very much! After slicing the data and storing it in the custom netCDF file, it worked!

**Comment by moisespr123** [comment]
Hi again,

I just noticed that while the Current file is working, the image renderers only shows a black dot sequence that seems to be a line. It seems the current file is being used as I can see some curves across the line, but it seems the spill isn't actually spreading. 

In comparison, when I use the RandomMover, the images have both black and red dots and the spill is spread.

The question that I have is, am I supposed to use both movers to generate a correct spill?

Thanks again,
-Moisés

**Comment by jay-hennen** [comment]
Yes that is correct.

**Comment by ChrisBarker-NOAA** [comment]
Exactly:

A Current Mover will move the elements with the currents -- if multiple elements start in the same place, they will be moved exactly the same way.

But in the real world, currents (and winds) have small fluctuations that are not captured in the model output, which serve to spread out, or diffuse things in the ocean.

We model that part of the process with a random walk scheme -- hence the RandomMover -- it adds a random fluctuation to the elements' positions, resulting in them spreading out. How. fast they spread depends on the diffusion coefficient used in the RandomMover.

**Comment by moisespr123** [comment]
Perfect. Thank you very much for your help!
