### ISSUE TITLE
problem to run py.test

### ISSUE THREAD

**Issue by farzanehashemabadi** [NOAA-ORR-ERD/PyGnome#78]
I built py_gnome 0.6.5 successfully on centOS 7, then I run py.test as (cd py_gnome/tests/unit_tests/py.test)  but have some Errors 
anyone can help me to fix it?

ImportError while loading conftest '/home/farzaneh.hashemabadi.student/install/PyGnome/py_gnome/tests/conftest.py'.
../conftest.py:15: in <module>
    from gnome.utilities import rand
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.                                        egg/gnome/__init__.py:116: in <module>
    from . import (environment,
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.                                        egg/gnome/model.py:18: in <module>
    from gnome.utilities.cache import ElementCache
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.                                        egg/gnome/utilities/cache.py:18: in <module>
    from gnome.spill_container import (SpillContainerData,
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.                                        egg/gnome/spill_container.py:21: in <module>
    import gnome.spill
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.                                        egg/gnome/spill/__init__.py:1: in <module>
    from spill import (Spill,
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.                                        egg/gnome/spill/spill.py:26: in <module>
    from .release import (Release,
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.                                        egg/gnome/spill/release.py:25: in <module>
    from gnome.outputters import NetCDFOutput
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.                                        egg/gnome/outputters/__init__.py:4: in <module>
    from renderer import Renderer, RendererSchema
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.                                        egg/gnome/outputters/renderer.py:14: in <module>
    import py_gd
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/py_gd/__init__.py:50: in <module>
    from py_gd import *
E   ImportError: /home/farzaneh.hashemabadi.student/.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packa                                        ges/scipy/sparse/../../../../libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/farzaneh.hashemabadi                                        .student/.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/py_gd/../../.././././libicuuc.so.58)

**Comment by ChrisBarker-NOAA** [comment]
this could be a tricky one, but here's where the real problem is -- right at the end:

```
import py_gd
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/py_gd/init.py:50: in
from py_gd import *
E ImportError: /home/farzaneh.hashemabadi.student/.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/sparse/../../../../libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/farzaneh.hashemabadi .student/.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/py_gd/../../.././././libicuuc.so.58)
```

This seems to be failing on import:

That *could* be a bug in the py_gd build -- which is maintained by us, with binaries hosted on conda-forge.

But the actual error seems to be coming from scipy, which is out of our hands.

The first thing I'd try is to see if scipy can be imported in your conda environment:

```
$ python -c "import scipy; print(scipy.__version__)"
1.2.1
```
if that works, try py_gd:

```
$ python -c "import py_gd; print(py_gd.__version__)"
0.1.7
```

Then post the results of "conda list"

also a long shot, but someone on the web had lick with updating conda:

```
conda deactivate
conda update conda
```

-CHB

**Comment by farzanehashemabadi** [comment]
thanks for your response. for debug py_gd build which binaries can help me?
also I run commands that you said and results are below.



![run](https://user-images.githubusercontent.com/71126340/106350745-877f4180-62ec-11eb-932f-164f5ee2af17.JPG)

**Comment by farzanehashemabadi** [comment]
I installed scipy=1.2.1, and again run py.test but have same Errors.

ImportError while loading conftest '/home/farzaneh.hashemabadi.student/install/PyGnome/py_gnome                                                              /tests/conftest.py'.
../conftest.py:15: in <module>
    from gnome.utilities import rand
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6                                                              .5-py2.7-linux-x86_64.egg/gnome/__init__.py:116: in <module>
    from . import (environment,
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6                                                              .5-py2.7-linux-x86_64.egg/gnome/model.py:18: in <module>
    from gnome.utilities.cache import ElementCache
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6                                                              .5-py2.7-linux-x86_64.egg/gnome/utilities/cache.py:18: in <module>
    from gnome.spill_container import (SpillContainerData,
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6                                                              .5-py2.7-linux-x86_64.egg/gnome/spill_container.py:21: in <module>
    import gnome.spill
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6                                                              .5-py2.7-linux-x86_64.egg/gnome/spill/__init__.py:1: in <module>
    from spill import (Spill,
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6                                                              .5-py2.7-linux-x86_64.egg/gnome/spill/spill.py:26: in <module>
    from .release import (Release,
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6                                                              .5-py2.7-linux-x86_64.egg/gnome/spill/release.py:25: in <module>
    from gnome.outputters import NetCDFOutput
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6                                                              .5-py2.7-linux-x86_64.egg/gnome/outputters/__init__.py:2: in <module>
    from outputter import Outputter, BaseOutputterSchema
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6                                                              .5-py2.7-linux-x86_64.egg/gnome/outputters/outputter.py:21: in <module>
    from gnome.utilities.surface_concentration import compute_surface_concentration
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/pyGnome-0.6                                                              .5-py2.7-linux-x86_64.egg/gnome/utilities/surface_concentration.py:11: in <module>
    from scipy.stats import gaussian_kde
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/stats                                                              /__init__.py:367: in <module>
    from .stats import *
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/stats                                                              /stats.py:173: in <module>
    from . import distributions
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/stats                                                              /distributions.py:10: in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/stats                                                              /_distn_infrastructure.py:16: in <module>
    from scipy.misc import doccer
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/misc/                                                              __init__.py:68: in <module>
    from scipy.interpolate._pade import pade as _pade
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/inter                                                              polate/__init__.py:175: in <module>
    from .interpolate import *
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/inter                                                              polate/interpolate.py:32: in <module>
    from .interpnd import _ndim_coords_from_arrays
interpnd.pyx:1: in init scipy.interpolate.interpnd
    ???
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/spati                                                              al/__init__.py:98: in <module>
    from .kdtree import *
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/spati                                                              al/kdtree.py:8: in <module>
    import scipy.sparse
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/spars                                                              e/__init__.py:231: in <module>
    from .csr import *
../../../../../.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/spars                                                              e/csr.py:15: in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
E   ImportError: /home/farzaneh.hashemabadi.student/.conda/envs/farzaneh.hashemabadi.student/li                                                              b/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/farzaneh.hashemabadi.stud                                                              ent/.conda/envs/farzaneh.hashemabadi.student/lib/python2.7/site-packages/scipy/sparse/_sparseto                                                              ols.so)

**Comment by farzanehashemabadi** [comment]
my problem is solved by install gcc package.

**Comment by ChrisBarker-NOAA** [comment]
glad you got it fixed -- and thanks for letting us know -- I'll remember
that in the future.

Was that a conda gcc package? or a yum-installed one?

-CHB

-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by farzanehashemabadi** [comment]
thanks, I Installed gcc with conda.
