### ISSUE TITLE
problem to build py_gnome

### ISSUE THREAD

**Issue by farzanehashemabadi** [NOAA-ORR-ERD/PyGnome#79]
I want install py_gnome on CentOS 7. I complete previous steps successfully. but in step "python setup.py install" I have the Error that show in below.

 File "setup.py", line 29, in <module>
    from git import Repo
ModuleNotFoundError: No module named 'git'

but in my Environment git is installed.
please help me. thanks

**Comment by ChrisBarker-NOAA** [comment]
Sorry for the confusion(s) that error is for the python package, not git itself.

conda install gitpython 

should do it.

But that's in the conda-requirements file -- so be sure to make sure you've got the whole environment installed.

NOTE: we've pretty behind on updating master -- I"d recommend that you use the develop branch at this point.

**Comment by ChrisBarker-NOAA** [comment]
please re-open if this continues to be a problem.
