### ISSUE TITLE
oil from library

### ISSUE THREAD

**Issue by MBendoni** [NOAA-ORR-ERD/PyGnome#83]
Hi,

I am quite new to pyGnome and I am trying to use oil properties from an oil type (ABU SAFAH, ARAMCO) that seems be in the library:
    /home/gnome/PyGnome/OilLibrary/build/lib/oil_library/OilLib

In my .py script I have:
`from oil_library import get_oil, get_oil_props`
and
`substanceType = get_oil('ABU SAFAH, ARAMCO')`
however, when I run the script I receive the message:
`sqlalchemy.orm.exc.NoResultFound: Oil with identifier "ABU SAFAH, ARAMCO", not found in database`

I do not understand where I make the mistake.
To install the library, I followed the procedure in 
   /home/gnome/PyGnome/OilLibrary/README.md

Thank you in advance for any hint,
Michele

**Comment by ChrisBarker-NOAA** [comment]
I just tried it, and it worked for me, both with the master and develop branch.

To test your installation, try:

pytest --pyargs oil_library 

(pytest needs to be installed -- if not: conda install pytest)

**Comment by MBendoni** [comment]
Thank you for the reply.
I checked and indeed I got two errors for test_oil_props.py and in test_utilities.py (see attached file). Two oil types are not found in the database. However I checked and it seems they are present in it. Attached the installation log in case it might be useful.

[errorLog.txt](https://github.com/NOAA-ORR-ERD/PyGnome/files/6104266/errorLog.txt)
[installLog.txt](https://github.com/NOAA-ORR-ERD/PyGnome/files/6104275/installLog.txt)

michele

**Comment by ChrisBarker-NOAA** [comment]
Does it work for any other oils? The test errors indicate that oils expected in the tests aren't there.

The install log says: "OilLibrary database exists - do not remake!"

So you should force a rebuild of the database:

python setup.py cleanall

should clean it out, and then you can re-run the install to get a fresh database.

Make sure to pull the latest version of the code as well.

-CHB

**Comment by MBendoni** [comment]
Thank you Chris for the int.

I updated the pygnome version and I tried to re-install the oil library database.
I got some errors related to specific packages:
`ImportError: No module named sqlalchemy`
`ImportError: No module named zope.sqlalchemy`

so I installed the packages and now I get the following error:
`AttributeError: 'SessionTransaction' object has no attribute '_iterate_parents'`

that it seems is due to the issue discussed in these posts:
https://github.com/zopefoundation/zope.sqlalchemy/issues/18
https://github.com/zopefoundation/zope.sqlalchemy/issues/15
and solved here:
https://github.com/zopefoundation/zope.sqlalchemy/pull/16/commits/a4426cf98a4d9d3f5b1f30a200ed992ead0cfd7a
by making a modification in /miniconda2/envs/gnome/lib/python2.7/site-packages/zope/sqlalchemy/datamanager.py

Then the installation of the oil library went fine:
`Installed /home/bendoni/miniconda2/envs/gnome/lib/python2.7/site-packages/oil_library-1.1.3-py2.7.egg`
`Processing dependencies for oil-library==1.1.3`
`Finished processing dependencies for oil-library==1.1.3`

In order to pass (only some warnings):
`pytest --pyargs oil_library`
 the pathlib package has to be installed

However, when I run my gnome script I get the error (I tried with several oils)
`INFO -    spill - line:211 - Failed to get_oil_props for <Oil("HIGH ISLAND, AMOCO")>. Use as is assuming has OilProps interface
Traceback (most recent call last):
  File "./script_05_oilType.py", line 113, in <module>
    model = make_model()
  File "./script_05_oilType.py", line 89, in make_model
    substance=substanceType)
  File "/home/bendoni/PyGnome/py_gnome/gnome/spill/spill.py", line 162, in __init__
    self.amount = amount
  File "/home/bendoni/PyGnome/py_gnome/gnome/spill/spill.py", line 289, in amount
    std_density = self.substance.standard_density #kg/m3
AttributeError: 'Oil' object has no attribute 'standard_density'`
I noticed there was issue#65 related to this error but I do not understand how to fix it

cheers,
Michele

**Comment by ChrisBarker-NOAA** [comment]
I've just updated the develop branch for both PyGNOME and OilLibrary -- I recommend you give that a try.

It's python 3.8 now -- and this is what's being actively developed.

**Comment by MBendoni** [comment]
I tried, I created the environment:
`conda create --name gnome python=3.8`
but the problem is that theconda_requirements.txt imposes to use python2.7 and other packages are downgraded as well.
If I go on with the procedure, I encounter the same issues mentioned before

I downloaded the most updated version of the code from here:
`git clone https://github.com/NOAA-ORR-ERD/PyGnome.git`
should I download it from somewhere else? or shoul I change che conda_requirements.txt?

Michele

**Comment by MBendoni** [comment]
I downloaded the develop branch for pygnome and oil_library and created a gnome env with python=3.8.
Both installations are ok, and the pytest --pyargs oil_library too, without the need to change any file.

However, I continue to have the following error:
`INFO -    spill - line:214 - Failed to get_oil_props for <Oil("HIGH ISLAND, AMOCO")>. Use as is assuming has OilProps interface`
`Traceback (most recent call last):`
`File "./script_05_oilType.py", line 114, in <module>
model = make_model()`
`File "./script_05_oilType.py", line 87, in make_model
    spill = Spill(release=releaseType,`
`File "/home/bendoni/PyGnome/py_gnome/gnome/spill/spill.py", line 166, in __init__
    self.amount = amount`
`File "/home/bendoni/PyGnome/py_gnome/gnome/spill/spill.py", line 293, in amount
    std_density = self.substance.standard_density #kg/m3`
`AttributeError: 'Oil' object has no attribute 'standard_density'`

I am wondering if I am making any mistake related to the coding part.
I get errors also with sample oils based on which one I choose. The oil_bahia works (the model runs)
`substanceType = GnomeOil('oil_bahia')`
whereas, if I take:
`substanceType = GnomeOil('oil_crude')`
I receive an error:
`UnboundLocalError: local variable 'bullwinkle_fraction' referenced before assignment`

Thank you for your time,
Michele

**Comment by ChrisBarker-NOAA** [comment]
I'm glad you got it working!

Sorry about the confusion, you got caught by a change in the API.

If you can remember where you saw the example of using:

```
substanceType = get_oil('HIGH ISLAND, AMOCO')
spill = Spill(amount=3000, units='kg', substance=substanceType, release=releaseType)
```
That would be helpful, so we can update the examples and documentation.

NOTE: the issue there is that get_oil returns an oil_library Oil object, which is similar to, but not quite the same as a GNOME "substance'.

**Comment by MBendoni** [comment]
Do not worry, I can understand the code is in continuous evolution.

Honestly, I do not remember if I found it in one of the available scripts. I now tried grep 'get_oil' on the py_gnome/script/ folder without results. Most probably I confused the oil_object with the substance by myself, as you mentioned. 

I would have another question (hopefully the last one for a while...) related to the possibility to create wind and/or wave object with multiple NetCDF files to feed weathering functions. Should I open another issue?

cheers,
Michele

**Comment by ChrisBarker-NOAA** [comment]
"the possibility to create wind and/or wave object with multiple NetCDF files to feed weathering functions"

Yes, that can be done -- though not getting the wave data from the files -- it can get wind from files, and waves computed from the winds.

Yes, please open another issue for that.
