### ISSUE TITLE
Error in run py.test --runslow tests/unit_tests

### ISSUE THREAD

**Issue by simomartini** [NOAA-ORR-ERD/PyGnome#87]
Hello, 
Following the instructions I managed to install pyGnome, but when I try to run the tests it gives me the following error:

`$HOME/pyGnome/py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/__init__.py:46: UserWarning: ERROR: The gridded package, version >= 0.2.4needs to be installed
  warnings.warn(msg)
/$HOME/pyGnome/py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/__init__.py:46: UserWarning: ERROR: The oil_library package, version >= 1.1.2needs to be installed
  warnings.warn(msg)
$HOME/pyGnome/py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/__init__.py:52: UserWarning: Version 2.6.3 of unit_conversion package is required, but actual version in module is 2.6.0
  warnings.warn(msg)`

It does not find the "requirements.txt" libraries I had previously installed.
For the installation I ran the command:
`pip install -r requirements.txt`
followed by 
`python setup.py install`

During the process of requirements installation I dowload and sussesfully install py_gd, gridded, oil_library and units_setup. But I don't understand why pygnome didn't find it. 

Could u help me with some suggestions?

Kind Regards 
Simone

**Comment by ChrisBarker-NOAA** [comment]
The unit_conversion Warning is a warning — you’ll probably be fine. Or you can install the latest version from the source:

https://github.com/NOAA-ORR-ERD/PyNUCOS

One of these days I’ll make it properly pip-installable.

-CHB


Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

**Comment by simomartini** [comment]
Thanks I checked and indeed the packages were installed correctly. But when I run the tests I get the following error messages:

`[martinis@login py_gnome]$ py.test --runslow tests/unit_tests
====================================================================================== test session starts =======================================================================================
platform linux2 -- Python 2.7.18, pytest-4.6.11, py-1.10.0, pluggy-0.13.1
rootdir: /.../pyGnome/PyGnome/py_gnome
plugins: timeout-1.4.2
collected 1181 items / 3 errors / 1178 selected

============================================================================================= ERRORS =============================================================================================
______________________________________________________________________ ERROR collecting tests/unit_tests/test_save_load.py _______________________________________________________________________
tests/unit_tests/test_save_load.py:158: in <module>
    MapFromBNA(testdata['MapFromBNA']['testmap'], 6),
../../py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/maps/map.py:1188: in __init__
    raster, projection = self.build_raster(land_polys, BB)
../../py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/maps/map.py:1225: in build_raster
    viewport=BB)
../../py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/utilities/map_canvas.py:96: in __init__
    self.create_images(preset_colors)
../../py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/utilities/map_canvas.py:214: in create_images
    self.fore_image = py_gd.Image(width=width, height=height,
E   AttributeError: 'module' object has no attribute 'Image'
___________________________________________________________________ ERROR collecting tests/unit_tests/test_update_from_dict.py ___________________________________________________________________
tests/unit_tests/test_update_from_dict.py:86: in <module>
    define_mdl(3)])
tests/unit_tests/test_update_from_dict.py:71: in define_mdl
    copy_l_mv = copy.deepcopy(l_mv)
../../py27/Python-2.7.18/install/lib/python2.7/copy.py:163: in deepcopy
    y = copier(x, memo)
../../py27/Python-2.7.18/install/lib/python2.7/copy.py:230: in _deepcopy_list
    y.append(deepcopy(a, memo))
../../py27/Python-2.7.18/install/lib/python2.7/copy.py:174: in deepcopy
    y = copier(memo)
../../py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/gnomeobject.py:214: in __deepcopy__
    obj_copy.__dict__ = copy.deepcopy(self.__dict__, memo)
../../py27/Python-2.7.18/install/lib/python2.7/copy.py:163: in deepcopy
    y = copier(x, memo)
../../py27/Python-2.7.18/install/lib/python2.7/copy.py:257: in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
../../py27/Python-2.7.18/install/lib/python2.7/copy.py:182: in deepcopy
    rv = reductor(2)
stringsource:2: in gnome.cy_gnome.cy_random_mover.CyRandomMover.__reduce_cython__
    ???
E   TypeError: no default __reduce__ due to non-trivial __cinit__
____________________________________________________________________ ERROR collecting tests/unit_tests/test_maps/test_map.py _____________________________________________________________________
tests/unit_tests/test_maps/test_map.py:481: in <module>
    class Test_MapfromBNA:
tests/unit_tests/test_maps/test_map.py:485: in Test_MapfromBNA
    bna_map = MapFromBNA(testbnamap, refloat_halflife=6, raster_size=1000)
../../py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/maps/map.py:1188: in __init__
    raster, projection = self.build_raster(land_polys, BB)
../../py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/maps/map.py:1225: in build_raster
    viewport=BB)
../../py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/utilities/map_canvas.py:96: in __init__
    self.create_images(preset_colors)
../../py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/utilities/map_canvas.py:214: in create_images
    self.fore_image = py_gd.Image(width=width, height=height,
E   AttributeError: 'module' object has no attribute 'Image'
---------------------------------------------------------------------------------------- Captured stdout -----------------------------------------------------------------------------------------
instaniating map: /.../pyGnome/PyGnome/py_gnome/tests/unit_tests/sample_data/MapBounds_Island.bna
======================================================================================== warnings summary ========================================================================================
/.../pyGnome/py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/multi_model_broadcast.py:18
  /.../pyGnome/py27/Python-2.7.18/install/lib/python2.7/site-packages/pyGnome-0.6.5-py2.7-linux-x86_64.egg/gnome/multi_model_broadcast.py:18: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
      Install tornado itself to use zmq with the tornado IOLoop.

    from zmq.eventloop import ioloop, zmqstream

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================== 1 warnings, 3 error in 5.91 seconds ===============================================================================`

Could it be an installation error? I installed py_gd via pip.

**Comment by ChrisBarker-NOAA** [comment]
py_gd requires compilation and the lib_gd libraries -- we provide a a conda package, but I"m not sure what happens if you pip install it. In any case, you'll probably not get the latest version. So:

I'd get it from the source from gitHub:

https://github.com/NOAA-ORR-ERD/py_gd

and then build it from source.

Same for unit_conversion, which you can get from the pynucos source here:

https://github.com/NOAA-ORR-ERD/PyNUCOS

and probably good to get the latest release of gridded as well:

https://github.com/NOAA-ORR-ERD/gridded

as for the zmq error -- I have not idea.

BTW: as you are doing all this, it would probably be better to use the develop branch, and Python3.8. It's almost done -- a bit more testing rquired, and then we'll be doing all future with with Python3.

**Comment by ChrisBarker-NOAA** [comment]
This should be all cleared up now -- at least if you start with master, and a clean conda environment.
