### ISSUE TITLE
Loading mover data on unstructured grid

### ISSUE THREAD

**Issue by mbgnl** [NOAA-ORR-ERD/PyGnome#93]
Hi,

I am facing some problems while loading a netCDF file of currents with pyGNOME. Data are on an unstructured grid.

I tried to load it with both GridCurrentMover and PyCurrentMover, but in both cases I got the following error:

```
  File "~/anaconda3/envs/gnome/lib/python3.8/site-packages/gridded/variable.py", line 371, in data
    raise ValueError("Data/grid shape mismatch: Data shape is {0}, "
ValueError: Data/grid shape mismatch: Data shape is (4, 18311), Grid shape is (18311,)
```

Here is the header of the netCDF file:

```
dimensions:
        node = 18311 ;
        level = 22 ;
        time = UNLIMITED ; // (4 currently)
        nbi = 4 ;
        nbnd = 3600 ;
variables:
        float lon(node) ;
                lon:units = "degrees_east" ;
                lon:standard_name = "longitude" ;
        float lat(node) ;
                lat:units = "degrees_north" ;
                lat:standard_name = "latitude" ;
        float level(level) ;
                level:units = "m" ;
                level:standard_name = "depth" ;
                level:description = "bottom of vertical layers" ;
                level:axis = "Z" ;
                level:positive = "down" ;
        float node_depth(node) ;
                node_depth:units = "m" ;
                node_depth:standard_name = "sea_floor_depth_below_sea_surface" ;
                node_depth:description = "total depth at nodes" ;
        double time(time) ;
                time:units = "seconds since 2020-01-01 00:00:00 UTC" ;
                time:standard_name = "time" ;
                time:calendar = "standard" ;
                time:axis = "T" ;
        float water_u(time, node, level) ;
                water_u:units = "m s-1" ;
                water_u:standard_name = "eastward_sea_water_velocity" ;
                water_u:valid_min = -10.f ;
                water_u:valid_max = 10.f ;
                water_u:_FillValue = -999.f ;
        float water_v(time, node, level) ;
                water_v:units = "m s-1" ;
                water_v:standard_name = "northward_sea_water_velocity" ;
                water_v:valid_min = -10.f ;
                water_v:valid_max = 10.f ;
                water_v:_FillValue = -999.f ;
        int bnd(nbnd, nbi) ;
                bnd:long_name = "Boundary Segment Node List" ;
                bnd:start_index = 1 ;

// global attributes:
                :Conventions = "CF-1.4" ;
                :title = "currents" ;
                :grid_type = "TRIANGULAR" ;
```

Could you please provide any help on how to solve this problem?
Thank you in advance,

Max

**Comment by mbgnl** [comment]
I tried to add some information about the grid topology following the UGRID conventions, but it still doesn't work.

The error is now
```
  File "~/anaconda3/envs/gnome/lib/python3.8/site-packages/numpy/core/_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```

Here is the header of the new netCDF file:

```
dimensions:
        node = 18311 ;
        level = 22 ;
        element = 33100 ;
        vertex = 3 ;
        time = UNLIMITED ; // (4 currently)
        nbi = 4 ;
        nbnd = 3600 ;
variables:
        float lon(node) ;
                lon:units = "degrees_east" ;
                lon:standard_name = "longitude" ;
        float lat(node) ;
                lat:units = "degrees_north" ;
                lat:standard_name = "latitude" ;
        float level(level) ;
                level:units = "m" ;
                level:standard_name = "depth" ;
                level:description = "bottom of vertical layers" ;
                level:axis = "Z" ;
                level:positive = "down" ;
        float node_depth(node) ;
                node_depth:units = "m" ;
                node_depth:standard_name = "sea_floor_depth_below_sea_surface" ;
                node_depth:description = "total depth at nodes" ;
        int element_index(element, vertex) ;
                element_index:long_name = "element index of nodes" ;
                element_index:description = "maps every element to its three vertices" ;
                element_index:cf_role = "face_node_connectivity" ;
                element_index:start_index = 0 ;
        int topology ;
                topology:cf_role = "mesh_topology" ;
                topology:long_name = "topology data of 2D unstructured mesh" ;
                topology:topology_dimension = 2 ;
                topology:node_coordinates = "lon lat node_depth" ;
                topology:face_node_connectivity = "element_index" ;
        double time(time) ;
                time:units = "seconds since 2020-01-01 00:00:00 UTC" ;
                time:standard_name = "time" ;
                time:calendar = "standard" ;
                time:axis = "T" ;
        float water_u(time, node, level) ;
                water_u:units = "m s-1" ;
                water_u:standard_name = "eastward_sea_water_velocity" ;
                water_u:valid_min = -10.f ;
                water_u:valid_max = 10.f ;
                water_u:_FillValue = -999.f ;
        float water_v(time, node, level) ;
                water_v:units = "m s-1" ;
                water_v:standard_name = "northward_sea_water_velocity" ;
                water_v:valid_min = -10.f ;
                water_v:valid_max = 10.f ;
                water_v:_FillValue = -999.f ;
        int bnd(nbnd, nbi) ;
                bnd:long_name = "Boundary Segment Node List" ;
                bnd:start_index = 1 ;

// global attributes:
                :Conventions = "UGRID-1.0" ;
                :grid_type = "TRIANGULAR" ;
```

Thank you for any help you can provide,

Max

**Comment by jay-hennen** [comment]
Hi Max,

I think the problem is the ordering of your data dimensions. It's currently a hard requirement that the 'time' and 'depth' dimensions come before the surface spatial dimensions ('node' in this case).

**Comment by mbgnl** [comment]
Thank you very much for the quick reply.

I've tried to permute the dimension order as  you suggested, but I still get the same error:

```
    curr_mover = movers.PyCurrentMover(curr_file)
  File "~/PyGnome/py_gnome/gnome/movers/py_current_movers.py", line 103, in __init__
    self.current = GridCurrent.from_netCDF(filename=self.filename,
  File "~/PyGnome/py_gnome/gnome/environment/gridded_objects_base.py", line 551, in from_netCDF
    return super().from_netCDF(*args, **kwargs)
  File "~/anaconda3/envs/gnome/lib/python3.8/site-packages/gridded/variable.py", line 841, in from_netCDF
    grid = Grid.from_netCDF(grid_file,
  File "~/PyGnome/py_gnome/gnome/environment/gridded_objects_base.py", line 369, in from_netCDF
    return gridded.grids.Grid.from_netCDF(*args, **kwargs)
  File "~/anaconda3/envs/gnome/lib/python3.8/site-packages/gridded/grids.py", line 477, in from_netCDF
    c = Grid._load_grid(filename, cls, dataset)
  File "~/anaconda3/envs/gnome/lib/python3.8/site-packages/gridded/grids.py", line 424, in _load_grid
    return grid_type.from_ncfile(filename)
  File "~/anaconda3/envs/gnome/lib/python3.8/site-packages/gridded/pyugrid/ugrid.py", line 167, in from_ncfile
    grid = klass()
  File "~/PyGnome/py_gnome/gnome/environment/gridded_objects_base.py", line 132, in __init__
    if lon is not None and lon.max() > 180:
  File "~/anaconda3/envs/gnome/lib/python3.8/site-packages/numpy/core/_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```

I suspect the problem is that pyGNOME struggles to understand how the grid is done. Is my interpretation correct?
Do you please have any other suggestion that could help me solve the problem?

Thanks,

Max

**Comment by jay-hennen** [comment]
Well there is a design conflict between the node attributes and the grid init I discovered thanks to this issue.

However, it looks like the root problem is the topology attribute, specifically the "node_depth" in the node coordinates. I think removing that would let it load correctly:

```
        int topology ;
                topology:cf_role = "mesh_topology" ;
                topology:long_name = "topology data of 2D unstructured mesh" ;
                topology:topology_dimension = 2 ;
                topology:node_coordinates = "lon lat **node_depth**" ;
                topology:face_node_connectivity = "element_index" ;
```

**Comment by mbgnl** [comment]
Thank you for your reply and help.

I am pleased to know this issue has been useful to you too.

Unfortunately, removing "node_depth" in the "node_coordinates" attribute does not solve the problem. I suspect there is a problem with the variable bnd(nbnd,nbi) and the relevant boundary information. May this be the issue?

Thanks,

Max

**Comment by mbgnl** [comment]
I managed to solve the problem with PyCurrentMover: there was an issue in my datafile, specifically in the variable bnd.

However, the same file does not work with GridCurrentMover. The error I get is
`Not all vertex points were used. Error reordering gridpoints into verdat format`

Any idea on the reason why this happens?

Thank you very much,

Max

**Comment by ChrisBarker-NOAA** [comment]
GridCurrentMover is the same code as is used in the Desktop GUI GNOME. It is perhaps pickier about exactly how the grid is defined. But it may well mean that something is wrong with the grid.

Have you tested to make sure is working well with PyCurrentMover? or only that it will load?

@coconnor8: Do you have any ideas?

NOTE: we may be able to help debug this if you provide a sample netcdf file -- ideally not too large!

**Comment by mbgnl** [comment]
> Have you tested to make sure is working well with PyCurrentMover? or only that it will load?

Yes, I have made some tests and the model appears to run correctly with PyCurrentMover. The spill trajectory is as expected and very different from the trajectories obtained by running the model with diffusion only.


> GridCurrentMover is the same code as is used in the Desktop GUI GNOME.

Indeed, that error message is the same I get with the Desktop GUI GNOME. I also wrote to Ms O'Connor by e-mail to ask her for help with GNOME Desktop. Using PyCurrentMover the error messages were different, so I thought there were two different problems with pyGNOME and GNOME Desktop, but now I have realized that the problem is likely to be the same.

> NOTE: we may be able to help debug this if you provide a sample netcdf file -- ideally not too large!

I submitted to Ms O'Connor a small example for which I got the same error message. She helped me solve the problem with that: there was a node numbering issue and my variables were not correctly named. However, the same corrections do not solve the problem with my original file (I have avoided submitting it because of its size). I am trying to inspect my grid to catch any possible issue in it, there must be something there.

As the problem now appears to be the same with pyGNOME and GNOME Desktop (and it is almost surely due to problems with my grid), if you prefer avoid discussing both here and by e-mail, we can just close this issue and continue by e-mail or vice versa (in case you think this may be useful for other GNOME users too). 

Thank you very much for your help!

Max

**Comment by mbgnl** [comment]
I have finally figured out what the problem was: I extracted the boundary segments from a grd file containing the boundary information, but in that file the nodes were numbered differently from the netCDF datafile. As I am not the person who constructed the grid, I was not aware of this bug in the data.

Making the appropriate corrections and thanks to the suggestions Ms O'Connor provided me with (basically I have renamed my current velocity variables to u and v, and I have shifted the node numbering in the variable 'bnd' of boundary segments so as it to make it start from 1), I have solved the problem. Now everything works correctly both with PyCurrentMover and with GridCurrentMover, as well as with GNOME Desktop.

Thanks so much for your assistance, you have been really helpful and kind.

Max

**Comment by ChrisBarker-NOAA** [comment]
Thanks for the report -- one note: PyCurrentMover is not currently doing anything with this boundary information, so that's why it worked there.

That being said, it would be nice if gridded gave a helpful warning for things like this. PR's / Issue accepted here:

https://github.com/NOAA-ORR-ERD/gridded

:-)
