### ISSUE TITLE
Mono Ethylene Glycol(MEG) tracking from a sub-sea MEG transport pipeline

### ISSUE THREAD

**Issue by DoctorHamzeh** [NOAA-ORR-ERD/PyGnome#97]
Dears
Oil Companies inject Mono Ethylene Glycol(MEG) into natural gas pipelines to inhibit gas hydrates formation in these pipelines. These pipelines are laid in sea bed from the shore to platforms in offshore. from the point of view of spill simulation and contingency plan,
Is it possible to simulate a trajectory of Mono Ethylene Glycol(MEG) spilled from a sub-sea MEG transport pipeline in GNOME Model?
MEG is miscible in water and its relative density is about 1.11.

Thank you in advance

**Comment by ChrisBarker-NOAA** [comment]
As MEG is miscible, you'll want to simulate it essentially as  passive tracer. That is, set your elements to be "non-weathings, and make sure to set the windage to zero.

Sorry we don't have any examples handy -- but if you give it a try, then post an issue here with questions, we'll try to get you going.

For the source, you can simply release it below the surface or wherever you like.

But if you want to simulate the Gas Plume, then you'll need a plume model like TAMOC.

The hand-off from TAMOC to GNOME may require some custom work -- we've been testing it with oil, which is not miscible, and thus forms droplets with a rise velocity.
