### ISSUE TITLE
Set the develop branch as the default branch?

### ISSUE THREAD

**Issue by moisespr123** [NOAA-ORR-ERD/PyGnome#98]
Just noticed that the `master` branch is still set as the default; however, new code is being pushed to the `develop` branch.

**Comment by ChrisBarker-NOAA** [comment]
Yeah, sorry about that, but master really is supposed to be the default branch.

We do our development on an internal system and then mirror it on gitHub. And our development process is to have master be mostly stable, while the real active development goes on in develop, which may be broken and any given moment. 

We are more or less following this model:

https://nvie.com/posts/a-successful-git-branching-model/

However, In recent months, we've had some disruptive changes on develop (like the py3 transition) and have done a poor job of updating master.

We did a mig merge at the end of last week, with a touch more testing, I'll push master to gitHub, and we'll be all caught up.



We should be merging into master any day now,

**Comment by ChrisBarker-NOAA** [comment]
master is now up to date -- and fully Py3 :-)

We'll try to keep things in sync more in the future.
